image: golang:1.18.2-alpine3.16
stages:
  - test
test:
  stage: test
  script:
    - apk add --update --no-cache build-base git openssh
    - git config --global "url.ssh://git@gitlab.kenda.com.tw:4222".insteadOf "https://gitlab.kenda.com.tw"
    - mkdir ~/.ssh
    - echo "${SSH_PRIVATE_KEY}" >> ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -Ht ecdsa -p 4222 gitlab.kenda.com.tw,192.1.1.159 >> ~/.ssh/known_hosts
    - go mod download
    - go vet ./...
    - go test -race $(go list ./...) -v -coverprofile .testCoverage.txt
    - go tool cover -func .testCoverage.txt
