// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mutation.proto

package kendaql

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MutationType int32

const (
	MutationType_MUTATION_TYPE_UNSPECIFIED MutationType = 0
	MutationType_INSERT                    MutationType = 1
	MutationType_UPDATE                    MutationType = 2
	MutationType_DELETE                    MutationType = 3
)

var MutationType_name = map[int32]string{
	0: "MUTATION_TYPE_UNSPECIFIED",
	1: "INSERT",
	2: "UPDATE",
	3: "DELETE",
}

var MutationType_value = map[string]int32{
	"MUTATION_TYPE_UNSPECIFIED": 0,
	"INSERT":                    1,
	"UPDATE":                    2,
	"DELETE":                    3,
}

func (x MutationType) String() string {
	return proto.EnumName(MutationType_name, int32(x))
}

func (MutationType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_abb5a9726058e37d, []int{0}
}

type MutationRequest struct {
	Db                   *Database   `protobuf:"bytes,1,opt,name=db,proto3" json:"db,omitempty"`
	Sqls                 []*Mutation `protobuf:"bytes,2,rep,name=sqls,proto3" json:"sqls,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *MutationRequest) Reset()         { *m = MutationRequest{} }
func (m *MutationRequest) String() string { return proto.CompactTextString(m) }
func (*MutationRequest) ProtoMessage()    {}
func (*MutationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_abb5a9726058e37d, []int{0}
}

func (m *MutationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MutationRequest.Unmarshal(m, b)
}
func (m *MutationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MutationRequest.Marshal(b, m, deterministic)
}
func (m *MutationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MutationRequest.Merge(m, src)
}
func (m *MutationRequest) XXX_Size() int {
	return xxx_messageInfo_MutationRequest.Size(m)
}
func (m *MutationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MutationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MutationRequest proto.InternalMessageInfo

func (m *MutationRequest) GetDb() *Database {
	if m != nil {
		return m.Db
	}
	return nil
}

func (m *MutationRequest) GetSqls() []*Mutation {
	if m != nil {
		return m.Sqls
	}
	return nil
}

type Mutation struct {
	Type                 MutationType  `protobuf:"varint,1,opt,name=type,proto3,enum=proto.dm.kendaql.MutationType" json:"type,omitempty"`
	Table                *Table        `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	Fields               []*Field      `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
	Filter               *LogicalGroup `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Mutation) Reset()         { *m = Mutation{} }
func (m *Mutation) String() string { return proto.CompactTextString(m) }
func (*Mutation) ProtoMessage()    {}
func (*Mutation) Descriptor() ([]byte, []int) {
	return fileDescriptor_abb5a9726058e37d, []int{1}
}

func (m *Mutation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Mutation.Unmarshal(m, b)
}
func (m *Mutation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Mutation.Marshal(b, m, deterministic)
}
func (m *Mutation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Mutation.Merge(m, src)
}
func (m *Mutation) XXX_Size() int {
	return xxx_messageInfo_Mutation.Size(m)
}
func (m *Mutation) XXX_DiscardUnknown() {
	xxx_messageInfo_Mutation.DiscardUnknown(m)
}

var xxx_messageInfo_Mutation proto.InternalMessageInfo

func (m *Mutation) GetType() MutationType {
	if m != nil {
		return m.Type
	}
	return MutationType_MUTATION_TYPE_UNSPECIFIED
}

func (m *Mutation) GetTable() *Table {
	if m != nil {
		return m.Table
	}
	return nil
}

func (m *Mutation) GetFields() []*Field {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *Mutation) GetFilter() *LogicalGroup {
	if m != nil {
		return m.Filter
	}
	return nil
}

type MutationReply struct {
	LastInsertId         *wrappers.Int64Value `protobuf:"bytes,1,opt,name=last_insert_id,json=lastInsertId,proto3" json:"last_insert_id,omitempty"`
	RowsAffected         *wrappers.Int64Value `protobuf:"bytes,2,opt,name=rows_affected,json=rowsAffected,proto3" json:"rows_affected,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *MutationReply) Reset()         { *m = MutationReply{} }
func (m *MutationReply) String() string { return proto.CompactTextString(m) }
func (*MutationReply) ProtoMessage()    {}
func (*MutationReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_abb5a9726058e37d, []int{2}
}

func (m *MutationReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MutationReply.Unmarshal(m, b)
}
func (m *MutationReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MutationReply.Marshal(b, m, deterministic)
}
func (m *MutationReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MutationReply.Merge(m, src)
}
func (m *MutationReply) XXX_Size() int {
	return xxx_messageInfo_MutationReply.Size(m)
}
func (m *MutationReply) XXX_DiscardUnknown() {
	xxx_messageInfo_MutationReply.DiscardUnknown(m)
}

var xxx_messageInfo_MutationReply proto.InternalMessageInfo

func (m *MutationReply) GetLastInsertId() *wrappers.Int64Value {
	if m != nil {
		return m.LastInsertId
	}
	return nil
}

func (m *MutationReply) GetRowsAffected() *wrappers.Int64Value {
	if m != nil {
		return m.RowsAffected
	}
	return nil
}

func init() {
	proto.RegisterEnum("proto.dm.kendaql.MutationType", MutationType_name, MutationType_value)
	proto.RegisterType((*MutationRequest)(nil), "proto.dm.kendaql.MutationRequest")
	proto.RegisterType((*Mutation)(nil), "proto.dm.kendaql.Mutation")
	proto.RegisterType((*MutationReply)(nil), "proto.dm.kendaql.MutationReply")
}

func init() { proto.RegisterFile("mutation.proto", fileDescriptor_abb5a9726058e37d) }

var fileDescriptor_abb5a9726058e37d = []byte{
	// 445 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x41, 0x6f, 0xd3, 0x30,
	0x1c, 0xc5, 0x49, 0x5a, 0x2a, 0x64, 0xb6, 0x12, 0xf9, 0x42, 0x56, 0x60, 0x9a, 0x7a, 0x42, 0x93,
	0xb0, 0xa5, 0x82, 0x76, 0x42, 0x88, 0x42, 0x33, 0x14, 0x69, 0x2b, 0x25, 0x73, 0x91, 0xe0, 0x12,
	0xd9, 0xb5, 0x1b, 0x45, 0x38, 0x71, 0x1a, 0x3b, 0x54, 0xfd, 0x1e, 0x7c, 0x36, 0x3e, 0x0f, 0x8a,
	0xe3, 0xc1, 0xc4, 0xba, 0x9d, 0x6c, 0xe5, 0xbd, 0x9f, 0xfd, 0xf2, 0xfc, 0x07, 0xc3, 0xa2, 0x31,
	0xd4, 0xe4, 0xaa, 0x44, 0x55, 0xad, 0x8c, 0x82, 0x81, 0x5d, 0x10, 0x2f, 0xd0, 0x0f, 0x51, 0x72,
	0xba, 0x91, 0xa3, 0xe3, 0x4c, 0xa9, 0x4c, 0x0a, 0x6c, 0x05, 0xd6, 0xac, 0xf1, 0xb6, 0xa6, 0x55,
	0x25, 0x6a, 0xdd, 0x11, 0xa3, 0x23, 0xbb, 0x60, 0x5e, 0x60, 0x47, 0x60, 0xce, 0x9c, 0xf4, 0xfc,
	0x96, 0xb4, 0xce, 0x85, 0xe4, 0x77, 0xaa, 0x86, 0x32, 0x29, 0x3a, 0x75, 0x5c, 0x80, 0x27, 0x97,
	0x2e, 0x5a, 0x22, 0x36, 0x8d, 0xd0, 0x06, 0x9e, 0x02, 0x9f, 0xb3, 0xd0, 0x3b, 0xf1, 0x5e, 0x3e,
	0x9e, 0x8c, 0xd0, 0xff, 0x41, 0xd1, 0x8c, 0x1a, 0xca, 0xa8, 0x16, 0x89, 0xcf, 0x19, 0x44, 0xa0,
	0xaf, 0x37, 0x52, 0x87, 0xfe, 0x49, 0x6f, 0xbf, 0xfb, 0xef, 0xe1, 0xd6, 0x37, 0xfe, 0xed, 0x81,
	0x47, 0xd7, 0x9f, 0xe0, 0x04, 0xf4, 0xcd, 0xae, 0x12, 0xf6, 0xaa, 0xe1, 0xe4, 0xf8, 0x6e, 0x98,
	0xec, 0x2a, 0x91, 0x58, 0x2f, 0x7c, 0x05, 0x1e, 0xda, 0xf8, 0xa1, 0x6f, 0xf3, 0x3d, 0xbd, 0x0d,
	0x91, 0x56, 0x4e, 0x3a, 0x17, 0xc4, 0x60, 0x60, 0xbb, 0xd0, 0x61, 0xcf, 0x26, 0xdc, 0xe3, 0x3f,
	0x6f, 0xf5, 0xc4, 0xd9, 0xe0, 0x59, 0x0b, 0x48, 0x23, 0xea, 0xb0, 0x6f, 0x2f, 0xd8, 0x93, 0xea,
	0x42, 0x65, 0xf9, 0x8a, 0xca, 0x4f, 0xb5, 0x6a, 0xaa, 0xc4, 0xb9, 0xc7, 0xbf, 0x3c, 0x70, 0xf8,
	0xaf, 0xc8, 0x4a, 0xee, 0xe0, 0x14, 0x0c, 0x25, 0xd5, 0x26, 0xcd, 0x4b, 0x2d, 0x6a, 0x93, 0xe6,
	0xdc, 0x55, 0xfa, 0x0c, 0x75, 0x2f, 0x8d, 0xae, 0x5f, 0x1a, 0xc5, 0xa5, 0x39, 0x7b, 0xf3, 0x95,
	0xca, 0x46, 0x24, 0x07, 0x2d, 0x12, 0x5b, 0x22, 0xe6, 0xf0, 0x3d, 0x38, 0xac, 0xd5, 0x56, 0xa7,
	0x74, 0xbd, 0x16, 0x2b, 0x23, 0xb8, 0xfb, 0xe9, 0xfb, 0x4f, 0x68, 0x89, 0xa9, 0x03, 0x4e, 0xbf,
	0x80, 0x83, 0x9b, 0x25, 0xc2, 0x17, 0xe0, 0xe8, 0x72, 0x49, 0xa6, 0x24, 0xfe, 0x3c, 0x4f, 0xc9,
	0xb7, 0x45, 0x94, 0x2e, 0xe7, 0x57, 0x8b, 0xe8, 0x63, 0x7c, 0x1e, 0x47, 0xb3, 0xe0, 0x01, 0x04,
	0x60, 0x10, 0xcf, 0xaf, 0xa2, 0x84, 0x04, 0x5e, 0xbb, 0x5f, 0x2e, 0x66, 0x53, 0x12, 0x05, 0x7e,
	0xbb, 0x9f, 0x45, 0x17, 0x11, 0x89, 0x82, 0xde, 0x87, 0x77, 0xdf, 0xdf, 0x66, 0xb9, 0x91, 0x94,
	0x75, 0x85, 0xa0, 0x95, 0x2a, 0x90, 0xd9, 0x76, 0xc3, 0x85, 0x57, 0xaa, 0x28, 0x54, 0xa9, 0xf1,
	0xcf, 0x49, 0x37, 0xc8, 0x38, 0x53, 0x92, 0x96, 0xd9, 0x8d, 0xe9, 0x63, 0x03, 0x2b, 0xbc, 0xfe,
	0x13, 0x00, 0x00, 0xff, 0xff, 0x61, 0xa5, 0x28, 0xd4, 0x13, 0x03, 0x00, 0x00,
}
