// Code generated by protoc-gen-go. DO NOT EDIT.
// source: add_meas_value.proto

package mes

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 新增
type AddMeasValueRequest struct {
	User                 string      `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Values               []*MeasItem `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AddMeasValueRequest) Reset()         { *m = AddMeasValueRequest{} }
func (m *AddMeasValueRequest) String() string { return proto.CompactTextString(m) }
func (*AddMeasValueRequest) ProtoMessage()    {}
func (*AddMeasValueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0936f8fcc07f0ecb, []int{0}
}

func (m *AddMeasValueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddMeasValueRequest.Unmarshal(m, b)
}
func (m *AddMeasValueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddMeasValueRequest.Marshal(b, m, deterministic)
}
func (m *AddMeasValueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddMeasValueRequest.Merge(m, src)
}
func (m *AddMeasValueRequest) XXX_Size() int {
	return xxx_messageInfo_AddMeasValueRequest.Size(m)
}
func (m *AddMeasValueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddMeasValueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddMeasValueRequest proto.InternalMessageInfo

func (m *AddMeasValueRequest) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *AddMeasValueRequest) GetValues() []*MeasItem {
	if m != nil {
		return m.Values
	}
	return nil
}

type AddMeasValueReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddMeasValueReply) Reset()         { *m = AddMeasValueReply{} }
func (m *AddMeasValueReply) String() string { return proto.CompactTextString(m) }
func (*AddMeasValueReply) ProtoMessage()    {}
func (*AddMeasValueReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_0936f8fcc07f0ecb, []int{1}
}

func (m *AddMeasValueReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddMeasValueReply.Unmarshal(m, b)
}
func (m *AddMeasValueReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddMeasValueReply.Marshal(b, m, deterministic)
}
func (m *AddMeasValueReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddMeasValueReply.Merge(m, src)
}
func (m *AddMeasValueReply) XXX_Size() int {
	return xxx_messageInfo_AddMeasValueReply.Size(m)
}
func (m *AddMeasValueReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AddMeasValueReply.DiscardUnknown(m)
}

var xxx_messageInfo_AddMeasValueReply proto.InternalMessageInfo

type MeasItem struct {
	EqptId               string   `protobuf:"bytes,1,opt,name=eqpt_id,json=eqptId,proto3" json:"eqpt_id,omitempty"`
	RecipeId             string   `protobuf:"bytes,2,opt,name=recipe_id,json=recipeId,proto3" json:"recipe_id,omitempty"`
	ShtId                string   `protobuf:"bytes,3,opt,name=sht_id,json=shtId,proto3" json:"sht_id,omitempty"`
	Item                 string   `protobuf:"bytes,4,opt,name=item,proto3" json:"item,omitempty"`
	Seqno                string   `protobuf:"bytes,5,opt,name=seqno,proto3" json:"seqno,omitempty"`
	Value                string   `protobuf:"bytes,6,opt,name=value,proto3" json:"value,omitempty"`
	Unit                 string   `protobuf:"bytes,7,opt,name=unit,proto3" json:"unit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MeasItem) Reset()         { *m = MeasItem{} }
func (m *MeasItem) String() string { return proto.CompactTextString(m) }
func (*MeasItem) ProtoMessage()    {}
func (*MeasItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_0936f8fcc07f0ecb, []int{2}
}

func (m *MeasItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MeasItem.Unmarshal(m, b)
}
func (m *MeasItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MeasItem.Marshal(b, m, deterministic)
}
func (m *MeasItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MeasItem.Merge(m, src)
}
func (m *MeasItem) XXX_Size() int {
	return xxx_messageInfo_MeasItem.Size(m)
}
func (m *MeasItem) XXX_DiscardUnknown() {
	xxx_messageInfo_MeasItem.DiscardUnknown(m)
}

var xxx_messageInfo_MeasItem proto.InternalMessageInfo

func (m *MeasItem) GetEqptId() string {
	if m != nil {
		return m.EqptId
	}
	return ""
}

func (m *MeasItem) GetRecipeId() string {
	if m != nil {
		return m.RecipeId
	}
	return ""
}

func (m *MeasItem) GetShtId() string {
	if m != nil {
		return m.ShtId
	}
	return ""
}

func (m *MeasItem) GetItem() string {
	if m != nil {
		return m.Item
	}
	return ""
}

func (m *MeasItem) GetSeqno() string {
	if m != nil {
		return m.Seqno
	}
	return ""
}

func (m *MeasItem) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *MeasItem) GetUnit() string {
	if m != nil {
		return m.Unit
	}
	return ""
}

func init() {
	proto.RegisterType((*AddMeasValueRequest)(nil), "proto.dm.mes.AddMeasValueRequest")
	proto.RegisterType((*AddMeasValueReply)(nil), "proto.dm.mes.AddMeasValueReply")
	proto.RegisterType((*MeasItem)(nil), "proto.dm.mes.MeasItem")
}

func init() { proto.RegisterFile("add_meas_value.proto", fileDescriptor_0936f8fcc07f0ecb) }

var fileDescriptor_0936f8fcc07f0ecb = []byte{
	// 280 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x50, 0xbd, 0x4e, 0xc3, 0x30,
	0x10, 0x56, 0xff, 0xd2, 0xd6, 0xb0, 0xe0, 0x16, 0xb0, 0xc4, 0x52, 0x65, 0xea, 0x64, 0x4b, 0x65,
	0x41, 0x6c, 0xb0, 0x65, 0x60, 0xc9, 0x80, 0x04, 0x4b, 0xe4, 0xc6, 0xa7, 0xd4, 0x22, 0xb6, 0x93,
	0xd8, 0x29, 0xe2, 0x99, 0x78, 0x49, 0xe4, 0x4b, 0x90, 0x60, 0xf2, 0x7d, 0x3f, 0xf7, 0xf9, 0xee,
	0xc8, 0x56, 0x2a, 0x55, 0x18, 0x90, 0xbe, 0x38, 0xcb, 0xba, 0x07, 0xde, 0x74, 0x2e, 0x38, 0x7a,
	0x89, 0x0f, 0x57, 0x86, 0x1b, 0xf0, 0xe9, 0x1b, 0xd9, 0x3c, 0x29, 0xf5, 0x02, 0xd2, 0xbf, 0x46,
	0x4f, 0x0e, 0x6d, 0x0f, 0x3e, 0x50, 0x4a, 0xe6, 0xbd, 0x87, 0x8e, 0x4d, 0x76, 0x93, 0xfd, 0x3a,
	0xc7, 0x9a, 0x72, 0x92, 0x60, 0x8e, 0x67, 0xd3, 0xdd, 0x6c, 0x7f, 0x71, 0xb8, 0xe1, 0x7f, 0x93,
	0x78, 0xcc, 0xc8, 0x02, 0x98, 0x7c, 0x74, 0xa5, 0x1b, 0x72, 0xf5, 0x3f, 0xba, 0xa9, 0xbf, 0xd2,
	0xef, 0x09, 0x59, 0xfd, 0x3a, 0xe9, 0x2d, 0x59, 0x42, 0xdb, 0x84, 0x42, 0xab, 0xf1, 0xa3, 0x24,
	0xc2, 0x4c, 0xd1, 0x3b, 0xb2, 0xee, 0xa0, 0xd4, 0x0d, 0x44, 0x69, 0x8a, 0xd2, 0x6a, 0x20, 0x32,
	0x45, 0xaf, 0x49, 0xe2, 0x4f, 0xd8, 0x34, 0x43, 0x65, 0xe1, 0x4f, 0xb1, 0x87, 0x92, 0xb9, 0x0e,
	0x60, 0xd8, 0x7c, 0x18, 0x39, 0xd6, 0x74, 0x4b, 0x16, 0x1e, 0x5a, 0xeb, 0xd8, 0x62, 0x74, 0x46,
	0x10, 0x59, 0x1c, 0x91, 0x25, 0x03, 0x8b, 0x00, 0x57, 0xb6, 0x3a, 0xb0, 0xe5, 0xb8, 0xb2, 0xd5,
	0xe1, 0xf9, 0xf1, 0xfd, 0xa1, 0xd2, 0xa1, 0x96, 0x47, 0xfe, 0x01, 0x56, 0x49, 0x5e, 0x3a, 0xc3,
	0xc3, 0xa7, 0x40, 0x20, 0x4a, 0x67, 0x8c, 0xb3, 0x5e, 0x9c, 0x0f, 0x02, 0x0f, 0x21, 0x2a, 0x57,
	0x4b, 0x5b, 0x09, 0x65, 0x84, 0x01, 0x7f, 0x4c, 0x90, 0xbc, 0xff, 0x09, 0x00, 0x00, 0xff, 0xff,
	0x51, 0xa3, 0x1b, 0x06, 0x86, 0x01, 0x00, 0x00,
}
