// Code generated by protoc-gen-go. DO NOT EDIT.
// source: carrier_material_operating.proto

package mes

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 查詢
type GetCarrierMaterialRequest struct {
	CrrId                string   `protobuf:"bytes,1,opt,name=crr_id,json=crrId,proto3" json:"crr_id,omitempty"`
	MtrlLotId            string   `protobuf:"bytes,2,opt,name=mtrl_lot_id,json=mtrlLotId,proto3" json:"mtrl_lot_id,omitempty"`
	MtrlProductId        string   `protobuf:"bytes,3,opt,name=mtrl_product_id,json=mtrlProductId,proto3" json:"mtrl_product_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCarrierMaterialRequest) Reset()         { *m = GetCarrierMaterialRequest{} }
func (m *GetCarrierMaterialRequest) String() string { return proto.CompactTextString(m) }
func (*GetCarrierMaterialRequest) ProtoMessage()    {}
func (*GetCarrierMaterialRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_360dc1d4391b18d1, []int{0}
}

func (m *GetCarrierMaterialRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCarrierMaterialRequest.Unmarshal(m, b)
}
func (m *GetCarrierMaterialRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCarrierMaterialRequest.Marshal(b, m, deterministic)
}
func (m *GetCarrierMaterialRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCarrierMaterialRequest.Merge(m, src)
}
func (m *GetCarrierMaterialRequest) XXX_Size() int {
	return xxx_messageInfo_GetCarrierMaterialRequest.Size(m)
}
func (m *GetCarrierMaterialRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCarrierMaterialRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCarrierMaterialRequest proto.InternalMessageInfo

func (m *GetCarrierMaterialRequest) GetCrrId() string {
	if m != nil {
		return m.CrrId
	}
	return ""
}

func (m *GetCarrierMaterialRequest) GetMtrlLotId() string {
	if m != nil {
		return m.MtrlLotId
	}
	return ""
}

func (m *GetCarrierMaterialRequest) GetMtrlProductId() string {
	if m != nil {
		return m.MtrlProductId
	}
	return ""
}

type GetCarrierMaterialReply struct {
	Mtrls                []*CrrMtrlInfo `protobuf:"bytes,1,rep,name=mtrls,proto3" json:"mtrls,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetCarrierMaterialReply) Reset()         { *m = GetCarrierMaterialReply{} }
func (m *GetCarrierMaterialReply) String() string { return proto.CompactTextString(m) }
func (*GetCarrierMaterialReply) ProtoMessage()    {}
func (*GetCarrierMaterialReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_360dc1d4391b18d1, []int{1}
}

func (m *GetCarrierMaterialReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCarrierMaterialReply.Unmarshal(m, b)
}
func (m *GetCarrierMaterialReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCarrierMaterialReply.Marshal(b, m, deterministic)
}
func (m *GetCarrierMaterialReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCarrierMaterialReply.Merge(m, src)
}
func (m *GetCarrierMaterialReply) XXX_Size() int {
	return xxx_messageInfo_GetCarrierMaterialReply.Size(m)
}
func (m *GetCarrierMaterialReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCarrierMaterialReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetCarrierMaterialReply proto.InternalMessageInfo

func (m *GetCarrierMaterialReply) GetMtrls() []*CrrMtrlInfo {
	if m != nil {
		return m.Mtrls
	}
	return nil
}

// 新增
type AddCarrierMaterialRequest struct {
	CrrId                string   `protobuf:"bytes,1,opt,name=crr_id,json=crrId,proto3" json:"crr_id,omitempty"`
	MtrlLotId            string   `protobuf:"bytes,2,opt,name=mtrl_lot_id,json=mtrlLotId,proto3" json:"mtrl_lot_id,omitempty"`
	MtrlProductId        string   `protobuf:"bytes,3,opt,name=mtrl_product_id,json=mtrlProductId,proto3" json:"mtrl_product_id,omitempty"`
	User                 string   `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddCarrierMaterialRequest) Reset()         { *m = AddCarrierMaterialRequest{} }
func (m *AddCarrierMaterialRequest) String() string { return proto.CompactTextString(m) }
func (*AddCarrierMaterialRequest) ProtoMessage()    {}
func (*AddCarrierMaterialRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_360dc1d4391b18d1, []int{2}
}

func (m *AddCarrierMaterialRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddCarrierMaterialRequest.Unmarshal(m, b)
}
func (m *AddCarrierMaterialRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddCarrierMaterialRequest.Marshal(b, m, deterministic)
}
func (m *AddCarrierMaterialRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddCarrierMaterialRequest.Merge(m, src)
}
func (m *AddCarrierMaterialRequest) XXX_Size() int {
	return xxx_messageInfo_AddCarrierMaterialRequest.Size(m)
}
func (m *AddCarrierMaterialRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddCarrierMaterialRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddCarrierMaterialRequest proto.InternalMessageInfo

func (m *AddCarrierMaterialRequest) GetCrrId() string {
	if m != nil {
		return m.CrrId
	}
	return ""
}

func (m *AddCarrierMaterialRequest) GetMtrlLotId() string {
	if m != nil {
		return m.MtrlLotId
	}
	return ""
}

func (m *AddCarrierMaterialRequest) GetMtrlProductId() string {
	if m != nil {
		return m.MtrlProductId
	}
	return ""
}

func (m *AddCarrierMaterialRequest) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

type AddCarrierMaterialReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddCarrierMaterialReply) Reset()         { *m = AddCarrierMaterialReply{} }
func (m *AddCarrierMaterialReply) String() string { return proto.CompactTextString(m) }
func (*AddCarrierMaterialReply) ProtoMessage()    {}
func (*AddCarrierMaterialReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_360dc1d4391b18d1, []int{3}
}

func (m *AddCarrierMaterialReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddCarrierMaterialReply.Unmarshal(m, b)
}
func (m *AddCarrierMaterialReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddCarrierMaterialReply.Marshal(b, m, deterministic)
}
func (m *AddCarrierMaterialReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddCarrierMaterialReply.Merge(m, src)
}
func (m *AddCarrierMaterialReply) XXX_Size() int {
	return xxx_messageInfo_AddCarrierMaterialReply.Size(m)
}
func (m *AddCarrierMaterialReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AddCarrierMaterialReply.DiscardUnknown(m)
}

var xxx_messageInfo_AddCarrierMaterialReply proto.InternalMessageInfo

// 修改
type UpdateCarrierMaterialRequest struct {
	Mtrls                []*CrrMtrlInfo `protobuf:"bytes,1,rep,name=mtrls,proto3" json:"mtrls,omitempty"`
	User                 string         `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *UpdateCarrierMaterialRequest) Reset()         { *m = UpdateCarrierMaterialRequest{} }
func (m *UpdateCarrierMaterialRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateCarrierMaterialRequest) ProtoMessage()    {}
func (*UpdateCarrierMaterialRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_360dc1d4391b18d1, []int{4}
}

func (m *UpdateCarrierMaterialRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCarrierMaterialRequest.Unmarshal(m, b)
}
func (m *UpdateCarrierMaterialRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCarrierMaterialRequest.Marshal(b, m, deterministic)
}
func (m *UpdateCarrierMaterialRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCarrierMaterialRequest.Merge(m, src)
}
func (m *UpdateCarrierMaterialRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateCarrierMaterialRequest.Size(m)
}
func (m *UpdateCarrierMaterialRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCarrierMaterialRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCarrierMaterialRequest proto.InternalMessageInfo

func (m *UpdateCarrierMaterialRequest) GetMtrls() []*CrrMtrlInfo {
	if m != nil {
		return m.Mtrls
	}
	return nil
}

func (m *UpdateCarrierMaterialRequest) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

type UpdateCarrierMaterialReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateCarrierMaterialReply) Reset()         { *m = UpdateCarrierMaterialReply{} }
func (m *UpdateCarrierMaterialReply) String() string { return proto.CompactTextString(m) }
func (*UpdateCarrierMaterialReply) ProtoMessage()    {}
func (*UpdateCarrierMaterialReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_360dc1d4391b18d1, []int{5}
}

func (m *UpdateCarrierMaterialReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCarrierMaterialReply.Unmarshal(m, b)
}
func (m *UpdateCarrierMaterialReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCarrierMaterialReply.Marshal(b, m, deterministic)
}
func (m *UpdateCarrierMaterialReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCarrierMaterialReply.Merge(m, src)
}
func (m *UpdateCarrierMaterialReply) XXX_Size() int {
	return xxx_messageInfo_UpdateCarrierMaterialReply.Size(m)
}
func (m *UpdateCarrierMaterialReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCarrierMaterialReply.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCarrierMaterialReply proto.InternalMessageInfo

// 刪除
type DeleteCarrierMaterialRequest struct {
	Mtrls                []*CrrMtrlInfo `protobuf:"bytes,1,rep,name=mtrls,proto3" json:"mtrls,omitempty"`
	User                 string         `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *DeleteCarrierMaterialRequest) Reset()         { *m = DeleteCarrierMaterialRequest{} }
func (m *DeleteCarrierMaterialRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteCarrierMaterialRequest) ProtoMessage()    {}
func (*DeleteCarrierMaterialRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_360dc1d4391b18d1, []int{6}
}

func (m *DeleteCarrierMaterialRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCarrierMaterialRequest.Unmarshal(m, b)
}
func (m *DeleteCarrierMaterialRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCarrierMaterialRequest.Marshal(b, m, deterministic)
}
func (m *DeleteCarrierMaterialRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCarrierMaterialRequest.Merge(m, src)
}
func (m *DeleteCarrierMaterialRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteCarrierMaterialRequest.Size(m)
}
func (m *DeleteCarrierMaterialRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCarrierMaterialRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCarrierMaterialRequest proto.InternalMessageInfo

func (m *DeleteCarrierMaterialRequest) GetMtrls() []*CrrMtrlInfo {
	if m != nil {
		return m.Mtrls
	}
	return nil
}

func (m *DeleteCarrierMaterialRequest) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

type DeleteCarrierMaterialReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCarrierMaterialReply) Reset()         { *m = DeleteCarrierMaterialReply{} }
func (m *DeleteCarrierMaterialReply) String() string { return proto.CompactTextString(m) }
func (*DeleteCarrierMaterialReply) ProtoMessage()    {}
func (*DeleteCarrierMaterialReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_360dc1d4391b18d1, []int{7}
}

func (m *DeleteCarrierMaterialReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCarrierMaterialReply.Unmarshal(m, b)
}
func (m *DeleteCarrierMaterialReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCarrierMaterialReply.Marshal(b, m, deterministic)
}
func (m *DeleteCarrierMaterialReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCarrierMaterialReply.Merge(m, src)
}
func (m *DeleteCarrierMaterialReply) XXX_Size() int {
	return xxx_messageInfo_DeleteCarrierMaterialReply.Size(m)
}
func (m *DeleteCarrierMaterialReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCarrierMaterialReply.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCarrierMaterialReply proto.InternalMessageInfo

type CrrMtrlInfo struct {
	CrrId                string   `protobuf:"bytes,1,opt,name=crr_id,json=crrId,proto3" json:"crr_id,omitempty"`
	MtrlLotId            string   `protobuf:"bytes,2,opt,name=mtrl_lot_id,json=mtrlLotId,proto3" json:"mtrl_lot_id,omitempty"`
	MtrlProductId        string   `protobuf:"bytes,3,opt,name=mtrl_product_id,json=mtrlProductId,proto3" json:"mtrl_product_id,omitempty"`
	UpdateAt             string   `protobuf:"bytes,4,opt,name=update_at,json=updateAt,proto3" json:"update_at,omitempty"`
	UpdateBy             string   `protobuf:"bytes,5,opt,name=update_by,json=updateBy,proto3" json:"update_by,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CrrMtrlInfo) Reset()         { *m = CrrMtrlInfo{} }
func (m *CrrMtrlInfo) String() string { return proto.CompactTextString(m) }
func (*CrrMtrlInfo) ProtoMessage()    {}
func (*CrrMtrlInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_360dc1d4391b18d1, []int{8}
}

func (m *CrrMtrlInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CrrMtrlInfo.Unmarshal(m, b)
}
func (m *CrrMtrlInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CrrMtrlInfo.Marshal(b, m, deterministic)
}
func (m *CrrMtrlInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CrrMtrlInfo.Merge(m, src)
}
func (m *CrrMtrlInfo) XXX_Size() int {
	return xxx_messageInfo_CrrMtrlInfo.Size(m)
}
func (m *CrrMtrlInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CrrMtrlInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CrrMtrlInfo proto.InternalMessageInfo

func (m *CrrMtrlInfo) GetCrrId() string {
	if m != nil {
		return m.CrrId
	}
	return ""
}

func (m *CrrMtrlInfo) GetMtrlLotId() string {
	if m != nil {
		return m.MtrlLotId
	}
	return ""
}

func (m *CrrMtrlInfo) GetMtrlProductId() string {
	if m != nil {
		return m.MtrlProductId
	}
	return ""
}

func (m *CrrMtrlInfo) GetUpdateAt() string {
	if m != nil {
		return m.UpdateAt
	}
	return ""
}

func (m *CrrMtrlInfo) GetUpdateBy() string {
	if m != nil {
		return m.UpdateBy
	}
	return ""
}

func init() {
	proto.RegisterType((*GetCarrierMaterialRequest)(nil), "proto.dm.mes.GetCarrierMaterialRequest")
	proto.RegisterType((*GetCarrierMaterialReply)(nil), "proto.dm.mes.GetCarrierMaterialReply")
	proto.RegisterType((*AddCarrierMaterialRequest)(nil), "proto.dm.mes.AddCarrierMaterialRequest")
	proto.RegisterType((*AddCarrierMaterialReply)(nil), "proto.dm.mes.AddCarrierMaterialReply")
	proto.RegisterType((*UpdateCarrierMaterialRequest)(nil), "proto.dm.mes.UpdateCarrierMaterialRequest")
	proto.RegisterType((*UpdateCarrierMaterialReply)(nil), "proto.dm.mes.UpdateCarrierMaterialReply")
	proto.RegisterType((*DeleteCarrierMaterialRequest)(nil), "proto.dm.mes.DeleteCarrierMaterialRequest")
	proto.RegisterType((*DeleteCarrierMaterialReply)(nil), "proto.dm.mes.DeleteCarrierMaterialReply")
	proto.RegisterType((*CrrMtrlInfo)(nil), "proto.dm.mes.CrrMtrlInfo")
}

func init() { proto.RegisterFile("carrier_material_operating.proto", fileDescriptor_360dc1d4391b18d1) }

var fileDescriptor_360dc1d4391b18d1 = []byte{
	// 354 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x51, 0x4d, 0x6b, 0xe3, 0x30,
	0x10, 0xc5, 0xf9, 0x62, 0xa3, 0xec, 0xb2, 0x60, 0x58, 0x62, 0x6f, 0x43, 0x09, 0x3e, 0x94, 0x9c,
	0x24, 0x48, 0x2f, 0xa5, 0xb7, 0x24, 0x85, 0xe2, 0xd2, 0x40, 0x09, 0xf4, 0xd2, 0x8b, 0x51, 0x2c,
	0xd5, 0x98, 0x4a, 0x96, 0x3b, 0x1e, 0xb7, 0xb8, 0x3f, 0xa2, 0x3f, 0xa3, 0xbf, 0xb3, 0x58, 0x0e,
	0xc5, 0x87, 0xe4, 0xd0, 0x43, 0xe8, 0x49, 0xd2, 0x7b, 0x6f, 0xf4, 0xde, 0xcc, 0x90, 0x69, 0xcc,
	0x01, 0x52, 0x09, 0x91, 0xe6, 0x28, 0x21, 0xe5, 0x2a, 0x32, 0xb9, 0x04, 0x8e, 0x69, 0x96, 0xd0,
	0x1c, 0x0c, 0x1a, 0xf7, 0xb7, 0x3d, 0xa8, 0xd0, 0x54, 0xcb, 0x22, 0x78, 0x23, 0xfe, 0xb5, 0xc4,
	0x55, 0x53, 0xb4, 0xde, 0xd5, 0x6c, 0xe4, 0x73, 0x29, 0x0b, 0x74, 0xff, 0x91, 0x41, 0x0c, 0x10,
	0xa5, 0xc2, 0x73, 0xa6, 0xce, 0x6c, 0xb8, 0xe9, 0xc7, 0x00, 0xa1, 0x70, 0x4f, 0xc9, 0x48, 0x23,
	0xa8, 0x48, 0x19, 0xac, 0xb9, 0x8e, 0xe5, 0x86, 0x35, 0x74, 0x6b, 0x30, 0x14, 0xee, 0x19, 0xf9,
	0x6b, 0xf9, 0x1c, 0x8c, 0x28, 0x63, 0xab, 0xe9, 0x5a, 0xcd, 0x9f, 0x1a, 0xbe, 0x6b, 0xd0, 0x50,
	0x04, 0x37, 0x64, 0xbc, 0xcf, 0x3b, 0x57, 0x95, 0xcb, 0x48, 0xbf, 0xd6, 0x16, 0x9e, 0x33, 0xed,
	0xce, 0x46, 0x73, 0x9f, 0xb6, 0x43, 0xd3, 0x15, 0xc0, 0x1a, 0x41, 0x85, 0xd9, 0xa3, 0xd9, 0x34,
	0xba, 0xe0, 0xdd, 0x21, 0xfe, 0x42, 0x88, 0x1f, 0x69, 0xc4, 0x75, 0x49, 0xaf, 0x2c, 0x24, 0x78,
	0x3d, 0x4b, 0xda, 0x7b, 0xe0, 0x93, 0xf1, 0xbe, 0x3c, 0xb9, 0xaa, 0x82, 0x98, 0x4c, 0xee, 0x73,
	0xc1, 0x51, 0x1e, 0x48, 0xfb, 0xdd, 0xe6, 0xbf, 0xfc, 0x3b, 0x2d, 0xff, 0x09, 0xf9, 0x7f, 0xc0,
	0x64, 0x17, 0xe1, 0x4a, 0x2a, 0x79, 0xf4, 0x08, 0x07, 0x4c, 0xea, 0x08, 0x1f, 0x0e, 0x19, 0xb5,
	0x3e, 0x3a, 0xf6, 0x8e, 0x4e, 0xc8, 0xb0, 0xb4, 0xf3, 0x88, 0x38, 0xee, 0x16, 0xf5, 0xab, 0x01,
	0x16, 0xd8, 0x22, 0xb7, 0x95, 0xd7, 0x6f, 0x93, 0xcb, 0x6a, 0x79, 0xf9, 0x70, 0x91, 0xa4, 0xa8,
	0xf8, 0x96, 0x3e, 0xc9, 0x4c, 0x70, 0x1a, 0x1b, 0x4d, 0xf1, 0x95, 0xd9, 0x07, 0x8b, 0x8d, 0xd6,
	0x26, 0x2b, 0xd8, 0xcb, 0x9c, 0xd9, 0x11, 0xb1, 0xc4, 0x28, 0x9e, 0x25, 0x4c, 0x68, 0xa6, 0x65,
	0xb1, 0x1d, 0x58, 0xf0, 0xfc, 0x33, 0x00, 0x00, 0xff, 0xff, 0x0c, 0x9c, 0xc7, 0x04, 0x97, 0x03,
	0x00, 0x00,
}
