// Code generated by protoc-gen-go. DO NOT EDIT.
// source: delete_materials.proto

package mes

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DeleteMaterialsRequest struct {
	Materials            []*DeleteMaterialsRequest_MaterialList `protobuf:"bytes,1,rep,name=materials,proto3" json:"materials,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-"`
	XXX_unrecognized     []byte                                 `json:"-"`
	XXX_sizecache        int32                                  `json:"-"`
}

func (m *DeleteMaterialsRequest) Reset()         { *m = DeleteMaterialsRequest{} }
func (m *DeleteMaterialsRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteMaterialsRequest) ProtoMessage()    {}
func (*DeleteMaterialsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d211125a8307cb, []int{0}
}

func (m *DeleteMaterialsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMaterialsRequest.Unmarshal(m, b)
}
func (m *DeleteMaterialsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMaterialsRequest.Marshal(b, m, deterministic)
}
func (m *DeleteMaterialsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMaterialsRequest.Merge(m, src)
}
func (m *DeleteMaterialsRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteMaterialsRequest.Size(m)
}
func (m *DeleteMaterialsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMaterialsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMaterialsRequest proto.InternalMessageInfo

func (m *DeleteMaterialsRequest) GetMaterials() []*DeleteMaterialsRequest_MaterialList {
	if m != nil {
		return m.Materials
	}
	return nil
}

type DeleteMaterialsRequest_MaterialList struct {
	ProductType          string   `protobuf:"bytes,1,opt,name=product_type,json=productType,proto3" json:"product_type,omitempty"`
	MtrlProductId        string   `protobuf:"bytes,2,opt,name=mtrl_product_id,json=mtrlProductId,proto3" json:"mtrl_product_id,omitempty"`
	MtrlLevel            string   `protobuf:"bytes,3,opt,name=mtrl_level,json=mtrlLevel,proto3" json:"mtrl_level,omitempty"`
	MtrlLotId            string   `protobuf:"bytes,4,opt,name=mtrl_lot_id,json=mtrlLotId,proto3" json:"mtrl_lot_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteMaterialsRequest_MaterialList) Reset()         { *m = DeleteMaterialsRequest_MaterialList{} }
func (m *DeleteMaterialsRequest_MaterialList) String() string { return proto.CompactTextString(m) }
func (*DeleteMaterialsRequest_MaterialList) ProtoMessage()    {}
func (*DeleteMaterialsRequest_MaterialList) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d211125a8307cb, []int{0, 0}
}

func (m *DeleteMaterialsRequest_MaterialList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMaterialsRequest_MaterialList.Unmarshal(m, b)
}
func (m *DeleteMaterialsRequest_MaterialList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMaterialsRequest_MaterialList.Marshal(b, m, deterministic)
}
func (m *DeleteMaterialsRequest_MaterialList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMaterialsRequest_MaterialList.Merge(m, src)
}
func (m *DeleteMaterialsRequest_MaterialList) XXX_Size() int {
	return xxx_messageInfo_DeleteMaterialsRequest_MaterialList.Size(m)
}
func (m *DeleteMaterialsRequest_MaterialList) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMaterialsRequest_MaterialList.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMaterialsRequest_MaterialList proto.InternalMessageInfo

func (m *DeleteMaterialsRequest_MaterialList) GetProductType() string {
	if m != nil {
		return m.ProductType
	}
	return ""
}

func (m *DeleteMaterialsRequest_MaterialList) GetMtrlProductId() string {
	if m != nil {
		return m.MtrlProductId
	}
	return ""
}

func (m *DeleteMaterialsRequest_MaterialList) GetMtrlLevel() string {
	if m != nil {
		return m.MtrlLevel
	}
	return ""
}

func (m *DeleteMaterialsRequest_MaterialList) GetMtrlLotId() string {
	if m != nil {
		return m.MtrlLotId
	}
	return ""
}

type DeleteMaterialsReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteMaterialsReply) Reset()         { *m = DeleteMaterialsReply{} }
func (m *DeleteMaterialsReply) String() string { return proto.CompactTextString(m) }
func (*DeleteMaterialsReply) ProtoMessage()    {}
func (*DeleteMaterialsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d211125a8307cb, []int{1}
}

func (m *DeleteMaterialsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMaterialsReply.Unmarshal(m, b)
}
func (m *DeleteMaterialsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMaterialsReply.Marshal(b, m, deterministic)
}
func (m *DeleteMaterialsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMaterialsReply.Merge(m, src)
}
func (m *DeleteMaterialsReply) XXX_Size() int {
	return xxx_messageInfo_DeleteMaterialsReply.Size(m)
}
func (m *DeleteMaterialsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMaterialsReply.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMaterialsReply proto.InternalMessageInfo

func init() {
	proto.RegisterType((*DeleteMaterialsRequest)(nil), "proto.dm.mes.DeleteMaterialsRequest")
	proto.RegisterType((*DeleteMaterialsRequest_MaterialList)(nil), "proto.dm.mes.DeleteMaterialsRequest.MaterialList")
	proto.RegisterType((*DeleteMaterialsReply)(nil), "proto.dm.mes.DeleteMaterialsReply")
}

func init() { proto.RegisterFile("delete_materials.proto", fileDescriptor_97d211125a8307cb) }

var fileDescriptor_97d211125a8307cb = []byte{
	// 264 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x41, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0xe9, 0x26, 0x42, 0x5f, 0x27, 0x42, 0x90, 0x52, 0x04, 0x65, 0xee, 0x20, 0x3b, 0x25,
	0x38, 0x2f, 0xe2, 0x51, 0xbc, 0x0c, 0x26, 0x4a, 0xf1, 0xe4, 0xa5, 0x64, 0xcd, 0xa3, 0x14, 0x93,
	0xa6, 0x36, 0x6f, 0x93, 0xde, 0xfd, 0x10, 0x7e, 0x5c, 0x69, 0x6a, 0xb5, 0xa0, 0xa7, 0x90, 0xdf,
	0xff, 0xf7, 0x7f, 0x24, 0x0f, 0x62, 0x85, 0x1a, 0x09, 0x33, 0x23, 0x09, 0x9b, 0x52, 0x6a, 0xc7,
	0xeb, 0xc6, 0x92, 0x65, 0x33, 0x7f, 0x70, 0x65, 0xb8, 0x41, 0xb7, 0xf8, 0x98, 0x40, 0x7c, 0xef,
	0xc5, 0x87, 0xc1, 0x4b, 0xf1, 0x6d, 0x87, 0x8e, 0xd8, 0x23, 0x84, 0x3f, 0xdd, 0x24, 0x98, 0x4f,
	0x97, 0xd1, 0xea, 0x8a, 0x8f, 0xcb, 0xfc, 0xff, 0x22, 0x1f, 0xc0, 0xa6, 0x74, 0x94, 0xfe, 0xce,
	0x38, 0xfd, 0x0c, 0x60, 0x36, 0xce, 0xd8, 0x05, 0x74, 0x8f, 0x51, 0xbb, 0x9c, 0x32, 0x6a, 0x6b,
	0x4c, 0x82, 0x79, 0xb0, 0x0c, 0xd3, 0xe8, 0x9b, 0x3d, 0xb7, 0x35, 0xb2, 0x4b, 0x38, 0x36, 0xd4,
	0xe8, 0x6c, 0xf0, 0x4a, 0x95, 0x4c, 0xbc, 0x75, 0xd4, 0xe1, 0xa7, 0x9e, 0xae, 0x15, 0x3b, 0x03,
	0xf0, 0x9e, 0xc6, 0x3d, 0xea, 0x64, 0xea, 0x95, 0xb0, 0x23, 0x9b, 0x0e, 0xb0, 0x73, 0x88, 0xfa,
	0xd8, 0xfa, 0x11, 0x07, 0xa3, 0xdc, 0xd2, 0x5a, 0x2d, 0x62, 0x38, 0xf9, 0xf3, 0x99, 0x5a, 0xb7,
	0x77, 0xb7, 0x2f, 0x37, 0x45, 0x49, 0x5a, 0x6e, 0xf9, 0x2b, 0x56, 0x4a, 0xf2, 0xdc, 0x1a, 0x4e,
	0xef, 0xc2, 0x5f, 0x44, 0x6e, 0x8d, 0xb1, 0x95, 0x13, 0xfb, 0x95, 0xf0, 0x6b, 0x11, 0x85, 0xd5,
	0xb2, 0x2a, 0x84, 0x32, 0xc2, 0xa0, 0xdb, 0x1e, 0x7a, 0x78, 0xfd, 0x15, 0x00, 0x00, 0xff, 0xff,
	0x27, 0xfb, 0xe8, 0x88, 0x89, 0x01, 0x00, 0x00,
}
