// Code generated by protoc-gen-go. DO NOT EDIT.
// source: get_container_by_container_type.proto

package mes

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetContainerByContypeRequest struct {
	EqptId               string   `protobuf:"bytes,1,opt,name=eqpt_id,json=eqptId,proto3" json:"eqpt_id,omitempty"`
	ConMtrlType          string   `protobuf:"bytes,2,opt,name=con_mtrl_type,json=conMtrlType,proto3" json:"con_mtrl_type,omitempty"`
	ConMtrlLevel         string   `protobuf:"bytes,3,opt,name=con_mtrl_level,json=conMtrlLevel,proto3" json:"con_mtrl_level,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetContainerByContypeRequest) Reset()         { *m = GetContainerByContypeRequest{} }
func (m *GetContainerByContypeRequest) String() string { return proto.CompactTextString(m) }
func (*GetContainerByContypeRequest) ProtoMessage()    {}
func (*GetContainerByContypeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8ff959ed8e9ea7d, []int{0}
}

func (m *GetContainerByContypeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetContainerByContypeRequest.Unmarshal(m, b)
}
func (m *GetContainerByContypeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetContainerByContypeRequest.Marshal(b, m, deterministic)
}
func (m *GetContainerByContypeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetContainerByContypeRequest.Merge(m, src)
}
func (m *GetContainerByContypeRequest) XXX_Size() int {
	return xxx_messageInfo_GetContainerByContypeRequest.Size(m)
}
func (m *GetContainerByContypeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetContainerByContypeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetContainerByContypeRequest proto.InternalMessageInfo

func (m *GetContainerByContypeRequest) GetEqptId() string {
	if m != nil {
		return m.EqptId
	}
	return ""
}

func (m *GetContainerByContypeRequest) GetConMtrlType() string {
	if m != nil {
		return m.ConMtrlType
	}
	return ""
}

func (m *GetContainerByContypeRequest) GetConMtrlLevel() string {
	if m != nil {
		return m.ConMtrlLevel
	}
	return ""
}

type GetContainerByContypeReply struct {
	Cotainers            []*GetContainerByContypeReply_List `protobuf:"bytes,1,rep,name=cotainers,proto3" json:"cotainers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *GetContainerByContypeReply) Reset()         { *m = GetContainerByContypeReply{} }
func (m *GetContainerByContypeReply) String() string { return proto.CompactTextString(m) }
func (*GetContainerByContypeReply) ProtoMessage()    {}
func (*GetContainerByContypeReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8ff959ed8e9ea7d, []int{1}
}

func (m *GetContainerByContypeReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetContainerByContypeReply.Unmarshal(m, b)
}
func (m *GetContainerByContypeReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetContainerByContypeReply.Marshal(b, m, deterministic)
}
func (m *GetContainerByContypeReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetContainerByContypeReply.Merge(m, src)
}
func (m *GetContainerByContypeReply) XXX_Size() int {
	return xxx_messageInfo_GetContainerByContypeReply.Size(m)
}
func (m *GetContainerByContypeReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetContainerByContypeReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetContainerByContypeReply proto.InternalMessageInfo

func (m *GetContainerByContypeReply) GetCotainers() []*GetContainerByContypeReply_List {
	if m != nil {
		return m.Cotainers
	}
	return nil
}

type GetContainerByContypeReply_List struct {
	ContainerId          string   `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetContainerByContypeReply_List) Reset()         { *m = GetContainerByContypeReply_List{} }
func (m *GetContainerByContypeReply_List) String() string { return proto.CompactTextString(m) }
func (*GetContainerByContypeReply_List) ProtoMessage()    {}
func (*GetContainerByContypeReply_List) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8ff959ed8e9ea7d, []int{1, 0}
}

func (m *GetContainerByContypeReply_List) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetContainerByContypeReply_List.Unmarshal(m, b)
}
func (m *GetContainerByContypeReply_List) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetContainerByContypeReply_List.Marshal(b, m, deterministic)
}
func (m *GetContainerByContypeReply_List) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetContainerByContypeReply_List.Merge(m, src)
}
func (m *GetContainerByContypeReply_List) XXX_Size() int {
	return xxx_messageInfo_GetContainerByContypeReply_List.Size(m)
}
func (m *GetContainerByContypeReply_List) XXX_DiscardUnknown() {
	xxx_messageInfo_GetContainerByContypeReply_List.DiscardUnknown(m)
}

var xxx_messageInfo_GetContainerByContypeReply_List proto.InternalMessageInfo

func (m *GetContainerByContypeReply_List) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

func init() {
	proto.RegisterType((*GetContainerByContypeRequest)(nil), "proto.dm.mes.GetContainerByContypeRequest")
	proto.RegisterType((*GetContainerByContypeReply)(nil), "proto.dm.mes.GetContainerByContypeReply")
	proto.RegisterType((*GetContainerByContypeReply_List)(nil), "proto.dm.mes.GetContainerByContypeReply.List")
}

func init() {
	proto.RegisterFile("get_container_by_container_type.proto", fileDescriptor_c8ff959ed8e9ea7d)
}

var fileDescriptor_c8ff959ed8e9ea7d = []byte{
	// 274 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xbf, 0x4e, 0xc3, 0x30,
	0x10, 0x87, 0x15, 0x8a, 0x8a, 0xea, 0x16, 0x06, 0x2f, 0x44, 0x15, 0x43, 0x89, 0x40, 0x2a, 0x03,
	0xb6, 0x54, 0x16, 0xc4, 0x58, 0x06, 0x54, 0x51, 0x96, 0x88, 0x89, 0x25, 0x4a, 0xec, 0x53, 0x14,
	0xe1, 0x7f, 0x8d, 0x8f, 0x22, 0x8f, 0xbc, 0x03, 0x0f, 0x8c, 0x62, 0x20, 0xed, 0xd2, 0xc9, 0xfe,
	0x7d, 0xf7, 0x9d, 0x75, 0x67, 0x72, 0x5d, 0x03, 0x16, 0xc2, 0x1a, 0x2c, 0x1b, 0x03, 0x6d, 0x51,
	0x85, 0xbd, 0x80, 0xc1, 0x01, 0x73, 0xad, 0x45, 0x4b, 0x27, 0xf1, 0x60, 0x52, 0x33, 0x0d, 0x3e,
	0xfb, 0x4a, 0xc8, 0xc5, 0x13, 0xe0, 0xe3, 0xbf, 0xb9, 0x0c, 0xdd, 0x35, 0x38, 0xc8, 0x61, 0xf3,
	0x01, 0x1e, 0xe9, 0x39, 0x39, 0x81, 0x8d, 0xc3, 0xa2, 0x91, 0x69, 0x32, 0x4b, 0xe6, 0xa3, 0x7c,
	0xd8, 0xc5, 0x95, 0xa4, 0x19, 0x39, 0x15, 0xd6, 0x14, 0x1a, 0x5b, 0x15, 0x9f, 0x4f, 0x8f, 0x62,
	0x79, 0x2c, 0xac, 0x79, 0xc1, 0x56, 0xbd, 0x06, 0x07, 0xf4, 0x8a, 0x9c, 0xf5, 0x8e, 0x82, 0x2d,
	0xa8, 0x74, 0x10, 0xa5, 0xc9, 0x9f, 0xb4, 0xee, 0x58, 0xf6, 0x9d, 0x90, 0xe9, 0x81, 0x19, 0x9c,
	0x0a, 0xf4, 0x99, 0x8c, 0x84, 0xfd, 0xad, 0xf8, 0x34, 0x99, 0x0d, 0xe6, 0xe3, 0xc5, 0x2d, 0xdb,
	0x5f, 0x82, 0x1d, 0x6e, 0x66, 0xeb, 0xc6, 0x63, 0xbe, 0xeb, 0x9f, 0xde, 0x90, 0xe3, 0x0e, 0xd1,
	0x4b, 0x32, 0xd9, 0xfd, 0x4e, 0xbf, 0xdb, 0xb8, 0x67, 0x2b, 0xb9, 0x7c, 0x78, 0xbb, 0xaf, 0x1b,
	0x54, 0x65, 0xc5, 0xde, 0xc1, 0xc8, 0x92, 0x09, 0xab, 0x19, 0x7e, 0xf2, 0x18, 0xb8, 0xb0, 0x5a,
	0x5b, 0xe3, 0xf9, 0x76, 0xc1, 0xe3, 0x28, 0xbc, 0xb6, 0xaa, 0x34, 0x35, 0x97, 0x9a, 0x6b, 0xf0,
	0xd5, 0x30, 0xc2, 0xbb, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6f, 0x51, 0x8a, 0xbe, 0x94, 0x01,
	0x00, 0x00,
}
