// Code generated by protoc-gen-go. DO NOT EDIT.
// source: modify_prepare_order_info.proto

package mes

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UpdatePrepareOrderInfoRequest struct {
	User                 string         `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Preps                []*UpdatePreps `protobuf:"bytes,2,rep,name=preps,proto3" json:"preps,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *UpdatePrepareOrderInfoRequest) Reset()         { *m = UpdatePrepareOrderInfoRequest{} }
func (m *UpdatePrepareOrderInfoRequest) String() string { return proto.CompactTextString(m) }
func (*UpdatePrepareOrderInfoRequest) ProtoMessage()    {}
func (*UpdatePrepareOrderInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbf276cabfff0308, []int{0}
}

func (m *UpdatePrepareOrderInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePrepareOrderInfoRequest.Unmarshal(m, b)
}
func (m *UpdatePrepareOrderInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePrepareOrderInfoRequest.Marshal(b, m, deterministic)
}
func (m *UpdatePrepareOrderInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePrepareOrderInfoRequest.Merge(m, src)
}
func (m *UpdatePrepareOrderInfoRequest) XXX_Size() int {
	return xxx_messageInfo_UpdatePrepareOrderInfoRequest.Size(m)
}
func (m *UpdatePrepareOrderInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePrepareOrderInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePrepareOrderInfoRequest proto.InternalMessageInfo

func (m *UpdatePrepareOrderInfoRequest) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *UpdatePrepareOrderInfoRequest) GetPreps() []*UpdatePreps {
	if m != nil {
		return m.Preps
	}
	return nil
}

type UpdatePreps struct {
	//廠別
	FtyId int32 `protobuf:"varint,1,opt,name=fty_id,json=ftyId,proto3" json:"fty_id,omitempty"`
	//工單號
	LotId string `protobuf:"bytes,2,opt,name=lot_id,json=lotId,proto3" json:"lot_id,omitempty"`
	//中間製品識別碼
	ProductId string `protobuf:"bytes,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	//製程類別 R「暫定」、N「正式」、P「試產」、T「試做」
	StageStatus int32 `protobuf:"varint,4,opt,name=stage_status,json=stageStatus,proto3" json:"stage_status,omitempty"`
	//中間製品生產版本
	MajorVersion string `protobuf:"bytes,5,opt,name=major_version,json=majorVersion,proto3" json:"major_version,omitempty"`
	//備料成品代號
	CrProcessName string `protobuf:"bytes,6,opt,name=cr_process_name,json=crProcessName,proto3" json:"cr_process_name,omitempty"`
	//備料成品代號
	NxProcessName string `protobuf:"bytes,7,opt,name=nx_process_name,json=nxProcessName,proto3" json:"nx_process_name,omitempty"`
	//排程機台
	ResvEqptId string `protobuf:"bytes,8,opt,name=resv_eqpt_id,json=resvEqptId,proto3" json:"resv_eqpt_id,omitempty"`
	//排程日期
	ResvDate string `protobuf:"bytes,9,opt,name=resv_date,json=resvDate,proto3" json:"resv_date,omitempty"`
	//排程班別
	ResvShift string `protobuf:"bytes,10,opt,name=resv_shift,json=resvShift,proto3" json:"resv_shift,omitempty"`
	//排程序號
	ShiftSeq string `protobuf:"bytes,11,opt,name=shift_seq,json=shiftSeq,proto3" json:"shift_seq,omitempty"`
	//備料狀態
	PrepStat string `protobuf:"bytes,12,opt,name=prep_stat,json=prepStat,proto3" json:"prep_stat,omitempty"`
	//備料日期
	PrepDate string `protobuf:"bytes,13,opt,name=prep_date,json=prepDate,proto3" json:"prep_date,omitempty"`
	//備料序號
	PrepSeqNo string `protobuf:"bytes,14,opt,name=prep_seq_no,json=prepSeqNo,proto3" json:"prep_seq_no,omitempty"`
	//須備料數量
	PlanOptQty float32 `protobuf:"fixed32,15,opt,name=plan_opt_qty,json=planOptQty,proto3" json:"plan_opt_qty,omitempty"`
	//已備料數量
	CompQty float32 `protobuf:"fixed32,16,opt,name=comp_qty,json=compQty,proto3" json:"comp_qty,omitempty"`
	//須備料首數
	PlanShtCnt int32 `protobuf:"varint,17,opt,name=plan_sht_cnt,json=planShtCnt,proto3" json:"plan_sht_cnt,omitempty"`
	//已備料首數
	CompShtCnt int32 `protobuf:"varint,18,opt,name=comp_sht_cnt,json=compShtCnt,proto3" json:"comp_sht_cnt,omitempty"`
	//更改日期
	UpdateAt string `protobuf:"bytes,19,opt,name=update_at,json=updateAt,proto3" json:"update_at,omitempty"`
	//更改者
	UpdateBy string `protobuf:"bytes,20,opt,name=update_by,json=updateBy,proto3" json:"update_by,omitempty"`
	//建立日期
	InsertAt string `protobuf:"bytes,21,opt,name=insert_at,json=insertAt,proto3" json:"insert_at,omitempty"`
	//建立者
	InsertBy string `protobuf:"bytes,22,opt,name=insert_by,json=insertBy,proto3" json:"insert_by,omitempty"`
	//備料類型
	PrepraeType          string   `protobuf:"bytes,23,opt,name=preprae_type,json=prepraeType,proto3" json:"preprae_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePreps) Reset()         { *m = UpdatePreps{} }
func (m *UpdatePreps) String() string { return proto.CompactTextString(m) }
func (*UpdatePreps) ProtoMessage()    {}
func (*UpdatePreps) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbf276cabfff0308, []int{1}
}

func (m *UpdatePreps) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePreps.Unmarshal(m, b)
}
func (m *UpdatePreps) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePreps.Marshal(b, m, deterministic)
}
func (m *UpdatePreps) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePreps.Merge(m, src)
}
func (m *UpdatePreps) XXX_Size() int {
	return xxx_messageInfo_UpdatePreps.Size(m)
}
func (m *UpdatePreps) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePreps.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePreps proto.InternalMessageInfo

func (m *UpdatePreps) GetFtyId() int32 {
	if m != nil {
		return m.FtyId
	}
	return 0
}

func (m *UpdatePreps) GetLotId() string {
	if m != nil {
		return m.LotId
	}
	return ""
}

func (m *UpdatePreps) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

func (m *UpdatePreps) GetStageStatus() int32 {
	if m != nil {
		return m.StageStatus
	}
	return 0
}

func (m *UpdatePreps) GetMajorVersion() string {
	if m != nil {
		return m.MajorVersion
	}
	return ""
}

func (m *UpdatePreps) GetCrProcessName() string {
	if m != nil {
		return m.CrProcessName
	}
	return ""
}

func (m *UpdatePreps) GetNxProcessName() string {
	if m != nil {
		return m.NxProcessName
	}
	return ""
}

func (m *UpdatePreps) GetResvEqptId() string {
	if m != nil {
		return m.ResvEqptId
	}
	return ""
}

func (m *UpdatePreps) GetResvDate() string {
	if m != nil {
		return m.ResvDate
	}
	return ""
}

func (m *UpdatePreps) GetResvShift() string {
	if m != nil {
		return m.ResvShift
	}
	return ""
}

func (m *UpdatePreps) GetShiftSeq() string {
	if m != nil {
		return m.ShiftSeq
	}
	return ""
}

func (m *UpdatePreps) GetPrepStat() string {
	if m != nil {
		return m.PrepStat
	}
	return ""
}

func (m *UpdatePreps) GetPrepDate() string {
	if m != nil {
		return m.PrepDate
	}
	return ""
}

func (m *UpdatePreps) GetPrepSeqNo() string {
	if m != nil {
		return m.PrepSeqNo
	}
	return ""
}

func (m *UpdatePreps) GetPlanOptQty() float32 {
	if m != nil {
		return m.PlanOptQty
	}
	return 0
}

func (m *UpdatePreps) GetCompQty() float32 {
	if m != nil {
		return m.CompQty
	}
	return 0
}

func (m *UpdatePreps) GetPlanShtCnt() int32 {
	if m != nil {
		return m.PlanShtCnt
	}
	return 0
}

func (m *UpdatePreps) GetCompShtCnt() int32 {
	if m != nil {
		return m.CompShtCnt
	}
	return 0
}

func (m *UpdatePreps) GetUpdateAt() string {
	if m != nil {
		return m.UpdateAt
	}
	return ""
}

func (m *UpdatePreps) GetUpdateBy() string {
	if m != nil {
		return m.UpdateBy
	}
	return ""
}

func (m *UpdatePreps) GetInsertAt() string {
	if m != nil {
		return m.InsertAt
	}
	return ""
}

func (m *UpdatePreps) GetInsertBy() string {
	if m != nil {
		return m.InsertBy
	}
	return ""
}

func (m *UpdatePreps) GetPrepraeType() string {
	if m != nil {
		return m.PrepraeType
	}
	return ""
}

type UpdatePrepareOrderInfoReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePrepareOrderInfoReply) Reset()         { *m = UpdatePrepareOrderInfoReply{} }
func (m *UpdatePrepareOrderInfoReply) String() string { return proto.CompactTextString(m) }
func (*UpdatePrepareOrderInfoReply) ProtoMessage()    {}
func (*UpdatePrepareOrderInfoReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbf276cabfff0308, []int{2}
}

func (m *UpdatePrepareOrderInfoReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePrepareOrderInfoReply.Unmarshal(m, b)
}
func (m *UpdatePrepareOrderInfoReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePrepareOrderInfoReply.Marshal(b, m, deterministic)
}
func (m *UpdatePrepareOrderInfoReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePrepareOrderInfoReply.Merge(m, src)
}
func (m *UpdatePrepareOrderInfoReply) XXX_Size() int {
	return xxx_messageInfo_UpdatePrepareOrderInfoReply.Size(m)
}
func (m *UpdatePrepareOrderInfoReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePrepareOrderInfoReply.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePrepareOrderInfoReply proto.InternalMessageInfo

func init() {
	proto.RegisterType((*UpdatePrepareOrderInfoRequest)(nil), "proto.dm.mes.UpdatePrepareOrderInfoRequest")
	proto.RegisterType((*UpdatePreps)(nil), "proto.dm.mes.UpdatePreps")
	proto.RegisterType((*UpdatePrepareOrderInfoReply)(nil), "proto.dm.mes.UpdatePrepareOrderInfoReply")
}

func init() { proto.RegisterFile("modify_prepare_order_info.proto", fileDescriptor_cbf276cabfff0308) }

var fileDescriptor_cbf276cabfff0308 = []byte{
	// 558 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x93, 0xcf, 0x72, 0xd3, 0x30,
	0x10, 0x87, 0xa7, 0x7f, 0xd2, 0x36, 0x4a, 0x4a, 0xc1, 0x50, 0x50, 0xa7, 0x53, 0x08, 0x65, 0x86,
	0xe9, 0xc9, 0x9e, 0x29, 0x17, 0x86, 0x1b, 0x05, 0x0e, 0xb9, 0xb4, 0x25, 0x01, 0x0e, 0x5c, 0x34,
	0x8a, 0xbd, 0x49, 0x0d, 0xb1, 0x24, 0x4b, 0x9b, 0x52, 0x3d, 0x2d, 0xaf, 0xc2, 0xec, 0x2a, 0xa1,
	0xe1, 0xc0, 0x29, 0xf1, 0xf7, 0xfd, 0x76, 0x25, 0xad, 0x2d, 0xf1, 0xa2, 0xb1, 0x55, 0x3d, 0x8d,
	0xca, 0x79, 0x70, 0xda, 0x83, 0xb2, 0xbe, 0x02, 0xaf, 0x6a, 0x33, 0xb5, 0xb9, 0xf3, 0x16, 0x6d,
	0xd6, 0xe7, 0x9f, 0xbc, 0x6a, 0xf2, 0x06, 0xc2, 0x69, 0x25, 0x4e, 0xbe, 0xba, 0x4a, 0x23, 0x5c,
	0xa7, 0xfc, 0x15, 0xc5, 0x87, 0x66, 0x6a, 0x47, 0xd0, 0x2e, 0x20, 0x60, 0x96, 0x89, 0xed, 0x45,
	0x00, 0x2f, 0x37, 0x06, 0x1b, 0x67, 0xdd, 0x11, 0xff, 0xcf, 0x0a, 0xd1, 0xa1, 0xf6, 0x41, 0x6e,
	0x0e, 0xb6, 0xce, 0x7a, 0xe7, 0x47, 0xf9, 0x7a, 0xcb, 0xfc, 0xbe, 0x5f, 0x18, 0xa5, 0xdc, 0xe9,
	0xef, 0x8e, 0xe8, 0xad, 0xe1, 0xec, 0x50, 0xec, 0x4c, 0x31, 0xaa, 0xba, 0xe2, 0xb6, 0x9d, 0x51,
	0x67, 0x8a, 0x71, 0x58, 0x11, 0x9e, 0x5b, 0x24, 0xbc, 0xc9, 0xab, 0x75, 0xe6, 0x16, 0x87, 0x55,
	0x76, 0x22, 0x84, 0xf3, 0xb6, 0x5a, 0x94, 0xac, 0xb6, 0x58, 0x75, 0x97, 0x64, 0x58, 0x65, 0x2f,
	0x45, 0x3f, 0xa0, 0x9e, 0x81, 0x0a, 0xa8, 0x71, 0x11, 0xe4, 0x36, 0xb7, 0xec, 0x31, 0x1b, 0x33,
	0xca, 0x5e, 0x89, 0xfd, 0x46, 0xff, 0xb0, 0x5e, 0xdd, 0x82, 0x0f, 0xb5, 0x35, 0xb2, 0xc3, 0x4d,
	0xfa, 0x0c, 0xbf, 0x25, 0x96, 0xbd, 0x16, 0x07, 0xa5, 0x57, 0xce, 0xdb, 0x12, 0x42, 0x50, 0x46,
	0x37, 0x20, 0x77, 0x38, 0xb6, 0x5f, 0xfa, 0xeb, 0x44, 0x2f, 0x75, 0x03, 0x94, 0x33, 0x77, 0xff,
	0xe6, 0x76, 0x53, 0xce, 0xdc, 0xad, 0xe7, 0x06, 0xa2, 0xef, 0x21, 0xdc, 0x2a, 0x68, 0x1d, 0x6f,
	0x7c, 0x8f, 0x43, 0x82, 0xd8, 0xa7, 0xd6, 0xd1, 0xce, 0x8f, 0x45, 0x97, 0x13, 0x34, 0x18, 0xd9,
	0x65, 0xbd, 0x47, 0xe0, 0xa3, 0x46, 0xa0, 0x53, 0xb3, 0x0c, 0x37, 0xf5, 0x14, 0xa5, 0x48, 0xa7,
	0x26, 0x32, 0x26, 0x40, 0xb5, 0x6c, 0x54, 0x80, 0x56, 0xf6, 0x52, 0x2d, 0x83, 0x31, 0xb4, 0x24,
	0x69, 0xf0, 0x3c, 0x11, 0xd9, 0x4f, 0x92, 0x00, 0x8d, 0xe3, 0xaf, 0xe4, 0x55, 0xf7, 0xef, 0x25,
	0xaf, 0xfa, 0x5c, 0xf4, 0x52, 0x25, 0xb4, 0xca, 0x58, 0xf9, 0x60, 0x35, 0x6c, 0x70, 0x63, 0x68,
	0x2f, 0x2d, 0x1d, 0xca, 0xcd, 0xb5, 0x51, 0xd6, 0xa1, 0x6a, 0x31, 0xca, 0x83, 0xc1, 0xc6, 0xd9,
	0xe6, 0x48, 0x10, 0xbb, 0x72, 0xf8, 0x19, 0x63, 0x76, 0x24, 0xf6, 0x4a, 0xdb, 0x38, 0xb6, 0x0f,
	0xd9, 0xee, 0xd2, 0x33, 0xa9, 0x55, 0x71, 0xb8, 0x41, 0x55, 0x1a, 0x94, 0x8f, 0xf8, 0x4d, 0x71,
	0xf1, 0xf8, 0x06, 0x3f, 0x18, 0xa4, 0x04, 0x17, 0xaf, 0x12, 0x59, 0x4a, 0x10, 0x5b, 0x26, 0x8e,
	0x45, 0x77, 0xc1, 0x5f, 0x92, 0xd2, 0x28, 0x1f, 0xa7, 0xdd, 0x27, 0xf0, 0x7e, 0x5d, 0x4e, 0xa2,
	0x7c, 0xb2, 0x2e, 0x2f, 0x22, 0xc9, 0xda, 0x04, 0xf0, 0x48, 0x95, 0x87, 0x49, 0x26, 0x90, 0x2a,
	0x97, 0x72, 0x12, 0xe5, 0xd3, 0x75, 0x79, 0x11, 0xe9, 0x0b, 0xa3, 0x09, 0x78, 0x0d, 0x0a, 0xa3,
	0x03, 0xf9, 0x8c, 0x7d, 0x6f, 0xc9, 0xbe, 0x44, 0x07, 0xa7, 0x27, 0xe2, 0xf8, 0x7f, 0xf7, 0xc8,
	0xcd, 0xe3, 0xc5, 0xbb, 0xef, 0x6f, 0x67, 0x35, 0xce, 0xf5, 0x24, 0xff, 0x09, 0xa6, 0xd2, 0x79,
	0x69, 0x9b, 0x1c, 0x7f, 0x15, 0xfc, 0x50, 0x94, 0xb6, 0x69, 0xac, 0x09, 0xc5, 0xed, 0x79, 0xc1,
	0x17, 0xa9, 0x98, 0xd9, 0xb9, 0x36, 0xb3, 0xa2, 0x6a, 0x8a, 0x06, 0xc2, 0x64, 0x87, 0xe1, 0x9b,
	0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x0a, 0xbf, 0xf1, 0x9e, 0xda, 0x03, 0x00, 0x00,
}
