// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mtrl_extended_record.proto

package prd

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MtrlExtendedRecordRequest struct {
	Subno                string   `protobuf:"bytes,1,opt,name=subno,proto3" json:"subno,omitempty"`
	Slipno               string   `protobuf:"bytes,2,opt,name=slipno,proto3" json:"slipno,omitempty"`
	Oldexpdate           string   `protobuf:"bytes,3,opt,name=oldexpdate,proto3" json:"oldexpdate,omitempty"`
	Expdate              string   `protobuf:"bytes,4,opt,name=expdate,proto3" json:"expdate,omitempty"`
	Usrno                string   `protobuf:"bytes,5,opt,name=usrno,proto3" json:"usrno,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MtrlExtendedRecordRequest) Reset()         { *m = MtrlExtendedRecordRequest{} }
func (m *MtrlExtendedRecordRequest) String() string { return proto.CompactTextString(m) }
func (*MtrlExtendedRecordRequest) ProtoMessage()    {}
func (*MtrlExtendedRecordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_523f376f0a08a9c6, []int{0}
}

func (m *MtrlExtendedRecordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MtrlExtendedRecordRequest.Unmarshal(m, b)
}
func (m *MtrlExtendedRecordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MtrlExtendedRecordRequest.Marshal(b, m, deterministic)
}
func (m *MtrlExtendedRecordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MtrlExtendedRecordRequest.Merge(m, src)
}
func (m *MtrlExtendedRecordRequest) XXX_Size() int {
	return xxx_messageInfo_MtrlExtendedRecordRequest.Size(m)
}
func (m *MtrlExtendedRecordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MtrlExtendedRecordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MtrlExtendedRecordRequest proto.InternalMessageInfo

func (m *MtrlExtendedRecordRequest) GetSubno() string {
	if m != nil {
		return m.Subno
	}
	return ""
}

func (m *MtrlExtendedRecordRequest) GetSlipno() string {
	if m != nil {
		return m.Slipno
	}
	return ""
}

func (m *MtrlExtendedRecordRequest) GetOldexpdate() string {
	if m != nil {
		return m.Oldexpdate
	}
	return ""
}

func (m *MtrlExtendedRecordRequest) GetExpdate() string {
	if m != nil {
		return m.Expdate
	}
	return ""
}

func (m *MtrlExtendedRecordRequest) GetUsrno() string {
	if m != nil {
		return m.Usrno
	}
	return ""
}

type MtrlExtendedRecordReply struct {
	Lists                []*MtrlExtendedList `protobuf:"bytes,1,rep,name=lists,proto3" json:"lists,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *MtrlExtendedRecordReply) Reset()         { *m = MtrlExtendedRecordReply{} }
func (m *MtrlExtendedRecordReply) String() string { return proto.CompactTextString(m) }
func (*MtrlExtendedRecordReply) ProtoMessage()    {}
func (*MtrlExtendedRecordReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_523f376f0a08a9c6, []int{1}
}

func (m *MtrlExtendedRecordReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MtrlExtendedRecordReply.Unmarshal(m, b)
}
func (m *MtrlExtendedRecordReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MtrlExtendedRecordReply.Marshal(b, m, deterministic)
}
func (m *MtrlExtendedRecordReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MtrlExtendedRecordReply.Merge(m, src)
}
func (m *MtrlExtendedRecordReply) XXX_Size() int {
	return xxx_messageInfo_MtrlExtendedRecordReply.Size(m)
}
func (m *MtrlExtendedRecordReply) XXX_DiscardUnknown() {
	xxx_messageInfo_MtrlExtendedRecordReply.DiscardUnknown(m)
}

var xxx_messageInfo_MtrlExtendedRecordReply proto.InternalMessageInfo

func (m *MtrlExtendedRecordReply) GetLists() []*MtrlExtendedList {
	if m != nil {
		return m.Lists
	}
	return nil
}

type MtrlExtendedList struct {
	Subno                string   `protobuf:"bytes,1,opt,name=subno,proto3" json:"subno,omitempty"`
	Slipno               string   `protobuf:"bytes,2,opt,name=slipno,proto3" json:"slipno,omitempty"`
	Oldexpdate           string   `protobuf:"bytes,3,opt,name=oldexpdate,proto3" json:"oldexpdate,omitempty"`
	Expdate              string   `protobuf:"bytes,4,opt,name=expdate,proto3" json:"expdate,omitempty"`
	Indat                string   `protobuf:"bytes,5,opt,name=indat,proto3" json:"indat,omitempty"`
	Intime               string   `protobuf:"bytes,6,opt,name=intime,proto3" json:"intime,omitempty"`
	Usrno                string   `protobuf:"bytes,7,opt,name=usrno,proto3" json:"usrno,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MtrlExtendedList) Reset()         { *m = MtrlExtendedList{} }
func (m *MtrlExtendedList) String() string { return proto.CompactTextString(m) }
func (*MtrlExtendedList) ProtoMessage()    {}
func (*MtrlExtendedList) Descriptor() ([]byte, []int) {
	return fileDescriptor_523f376f0a08a9c6, []int{2}
}

func (m *MtrlExtendedList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MtrlExtendedList.Unmarshal(m, b)
}
func (m *MtrlExtendedList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MtrlExtendedList.Marshal(b, m, deterministic)
}
func (m *MtrlExtendedList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MtrlExtendedList.Merge(m, src)
}
func (m *MtrlExtendedList) XXX_Size() int {
	return xxx_messageInfo_MtrlExtendedList.Size(m)
}
func (m *MtrlExtendedList) XXX_DiscardUnknown() {
	xxx_messageInfo_MtrlExtendedList.DiscardUnknown(m)
}

var xxx_messageInfo_MtrlExtendedList proto.InternalMessageInfo

func (m *MtrlExtendedList) GetSubno() string {
	if m != nil {
		return m.Subno
	}
	return ""
}

func (m *MtrlExtendedList) GetSlipno() string {
	if m != nil {
		return m.Slipno
	}
	return ""
}

func (m *MtrlExtendedList) GetOldexpdate() string {
	if m != nil {
		return m.Oldexpdate
	}
	return ""
}

func (m *MtrlExtendedList) GetExpdate() string {
	if m != nil {
		return m.Expdate
	}
	return ""
}

func (m *MtrlExtendedList) GetIndat() string {
	if m != nil {
		return m.Indat
	}
	return ""
}

func (m *MtrlExtendedList) GetIntime() string {
	if m != nil {
		return m.Intime
	}
	return ""
}

func (m *MtrlExtendedList) GetUsrno() string {
	if m != nil {
		return m.Usrno
	}
	return ""
}

func init() {
	proto.RegisterType((*MtrlExtendedRecordRequest)(nil), "proto.dm.prd.MtrlExtendedRecordRequest")
	proto.RegisterType((*MtrlExtendedRecordReply)(nil), "proto.dm.prd.MtrlExtendedRecordReply")
	proto.RegisterType((*MtrlExtendedList)(nil), "proto.dm.prd.mtrlExtendedList")
}

func init() { proto.RegisterFile("mtrl_extended_record.proto", fileDescriptor_523f376f0a08a9c6) }

var fileDescriptor_523f376f0a08a9c6 = []byte{
	// 285 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x90, 0xc1, 0x4a, 0xf4, 0x30,
	0x14, 0x85, 0xe9, 0x3f, 0x7f, 0x3b, 0x18, 0x5d, 0x48, 0x10, 0x8d, 0x2e, 0x86, 0xa1, 0xab, 0x59,
	0x25, 0x30, 0xba, 0x10, 0x97, 0x82, 0x3b, 0x45, 0xe8, 0xd2, 0xcd, 0xd0, 0x36, 0xa1, 0x04, 0x93,
	0xdc, 0x98, 0xdc, 0xea, 0xf8, 0x28, 0xbe, 0x8c, 0xcf, 0x26, 0x93, 0x4e, 0xb1, 0x88, 0x6b, 0x57,
	0xe5, 0xbb, 0xe7, 0x94, 0x93, 0x73, 0xc8, 0x85, 0xc5, 0x60, 0x36, 0x6a, 0x8b, 0xca, 0x49, 0x25,
	0x37, 0x41, 0xb5, 0x10, 0x24, 0xf7, 0x01, 0x10, 0xe8, 0x51, 0xfa, 0x70, 0x69, 0xb9, 0x0f, 0xb2,
	0xfc, 0xc8, 0xc8, 0xf9, 0x03, 0x06, 0x73, 0xb7, 0xf7, 0x56, 0xc9, 0x5a, 0xa9, 0x97, 0x5e, 0x45,
	0xa4, 0x27, 0x24, 0x8f, 0x7d, 0xe3, 0x80, 0x65, 0xcb, 0x6c, 0x75, 0x50, 0x0d, 0x40, 0x4f, 0x49,
	0x11, 0x8d, 0xf6, 0x0e, 0xd8, 0xbf, 0x74, 0xde, 0x13, 0x5d, 0x10, 0x02, 0x46, 0xaa, 0xad, 0x97,
	0x35, 0x2a, 0x36, 0x4b, 0xda, 0xe4, 0x42, 0x19, 0x99, 0x8f, 0xe2, 0xff, 0x24, 0x8e, 0xb8, 0xcb,
	0xe9, 0x63, 0x70, 0xc0, 0xf2, 0x21, 0x27, 0x41, 0xf9, 0x48, 0xce, 0x7e, 0x7b, 0x9a, 0x37, 0xef,
	0xf4, 0x8a, 0xe4, 0x46, 0x47, 0x8c, 0x2c, 0x5b, 0xce, 0x56, 0x87, 0xeb, 0x05, 0x9f, 0x96, 0xe2,
	0x76, 0xf2, 0xd7, 0xbd, 0x8e, 0x58, 0x0d, 0xe6, 0xf2, 0x33, 0x23, 0xc7, 0x3f, 0xb5, 0xbf, 0xec,
	0xa8, 0x9d, 0xac, 0x71, 0xec, 0x98, 0x60, 0x97, 0xa3, 0x1d, 0x6a, 0xab, 0x58, 0x31, 0xe4, 0x0c,
	0xf4, 0xbd, 0xc8, 0x7c, 0xb2, 0xc8, 0xed, 0xcd, 0xd3, 0x75, 0xa7, 0xd1, 0xd4, 0x0d, 0x7f, 0x56,
	0x4e, 0xd6, 0xbc, 0x05, 0xcb, 0xf1, 0x4d, 0x24, 0x10, 0x2d, 0x58, 0x0b, 0x2e, 0x8a, 0xd7, 0xb5,
	0x48, 0x6b, 0x88, 0x0e, 0x4c, 0xed, 0x3a, 0x21, 0xad, 0xf0, 0x41, 0x36, 0x45, 0x3a, 0x5e, 0x7e,
	0x05, 0x00, 0x00, 0xff, 0xff, 0x39, 0xe2, 0x1d, 0xa6, 0x1c, 0x02, 0x00, 0x00,
}
