// Code generated by protoc-gen-go. DO NOT EDIT.
// source: container_operating.proto

package mes

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	rs "gitlab.kenda.com.tw/kenda/commons/v2/proto/golang/dm/rs"
	container "gitlab.kenda.com.tw/kenda/commons/v2/proto/golang/dm/rs/container"
	code "gitlab.kenda.com.tw/kenda/commons/v2/proto/golang/mes/code"
	error1 "gitlab.kenda.com.tw/kenda/commons/v2/proto/golang/mes/code/error"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ContainerOperatingRequest struct {
	ActionType           code.FunctionModel   `protobuf:"varint,1,opt,name=action_type,json=actionType,proto3,enum=proto.mes.code.FunctionModel" json:"action_type,omitempty"`
	ContainerId          string               `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	OwnedFactoryId       rs.FactoryID         `protobuf:"varint,3,opt,name=owned_factory_id,json=ownedFactoryId,proto3,enum=proto.dm.rs.FactoryID" json:"owned_factory_id,omitempty"`
	OwnedDepartmentId    string               `protobuf:"bytes,4,opt,name=owned_department_id,json=ownedDepartmentId,proto3" json:"owned_department_id,omitempty"`
	Status               code.ContainerStatus `protobuf:"varint,5,opt,name=status,proto3,enum=proto.mes.code.ContainerStatus" json:"status,omitempty"`
	ContainerType        container.Type       `protobuf:"varint,6,opt,name=container_type,json=containerType,proto3,enum=proto.dm.rs.container.Type" json:"container_type,omitempty"`
	UpdateBy             string               `protobuf:"bytes,7,opt,name=update_by,json=updateBy,proto3" json:"update_by,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ContainerOperatingRequest) Reset()         { *m = ContainerOperatingRequest{} }
func (m *ContainerOperatingRequest) String() string { return proto.CompactTextString(m) }
func (*ContainerOperatingRequest) ProtoMessage()    {}
func (*ContainerOperatingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_044c5730faf9ff1e, []int{0}
}

func (m *ContainerOperatingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContainerOperatingRequest.Unmarshal(m, b)
}
func (m *ContainerOperatingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContainerOperatingRequest.Marshal(b, m, deterministic)
}
func (m *ContainerOperatingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContainerOperatingRequest.Merge(m, src)
}
func (m *ContainerOperatingRequest) XXX_Size() int {
	return xxx_messageInfo_ContainerOperatingRequest.Size(m)
}
func (m *ContainerOperatingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ContainerOperatingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ContainerOperatingRequest proto.InternalMessageInfo

func (m *ContainerOperatingRequest) GetActionType() code.FunctionModel {
	if m != nil {
		return m.ActionType
	}
	return code.FunctionModel_FUNCTION_MODEL_UNSPECIFIED
}

func (m *ContainerOperatingRequest) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

func (m *ContainerOperatingRequest) GetOwnedFactoryId() rs.FactoryID {
	if m != nil {
		return m.OwnedFactoryId
	}
	return rs.FactoryID_FACTORY_UNSPECIFIED
}

func (m *ContainerOperatingRequest) GetOwnedDepartmentId() string {
	if m != nil {
		return m.OwnedDepartmentId
	}
	return ""
}

func (m *ContainerOperatingRequest) GetStatus() code.ContainerStatus {
	if m != nil {
		return m.Status
	}
	return code.ContainerStatus_CONTAINER_STATUS_UNSPECIFIED
}

func (m *ContainerOperatingRequest) GetContainerType() container.Type {
	if m != nil {
		return m.ContainerType
	}
	return container.Type_CONTAINER_TYPE_UNSPECIFIED
}

func (m *ContainerOperatingRequest) GetUpdateBy() string {
	if m != nil {
		return m.UpdateBy
	}
	return ""
}

type ContainerOperatingReply struct {
	Err                  error1.ContainerIdOperating              `protobuf:"varint,1,opt,name=err,proto3,enum=proto.mes.code.error.ContainerIdOperating" json:"err,omitempty"`
	ContainerInfo        []*ContainerOperatingReply_ContainerInfo `protobuf:"bytes,2,rep,name=containerInfo,proto3" json:"containerInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                 `json:"-"`
	XXX_unrecognized     []byte                                   `json:"-"`
	XXX_sizecache        int32                                    `json:"-"`
}

func (m *ContainerOperatingReply) Reset()         { *m = ContainerOperatingReply{} }
func (m *ContainerOperatingReply) String() string { return proto.CompactTextString(m) }
func (*ContainerOperatingReply) ProtoMessage()    {}
func (*ContainerOperatingReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_044c5730faf9ff1e, []int{1}
}

func (m *ContainerOperatingReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContainerOperatingReply.Unmarshal(m, b)
}
func (m *ContainerOperatingReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContainerOperatingReply.Marshal(b, m, deterministic)
}
func (m *ContainerOperatingReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContainerOperatingReply.Merge(m, src)
}
func (m *ContainerOperatingReply) XXX_Size() int {
	return xxx_messageInfo_ContainerOperatingReply.Size(m)
}
func (m *ContainerOperatingReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ContainerOperatingReply.DiscardUnknown(m)
}

var xxx_messageInfo_ContainerOperatingReply proto.InternalMessageInfo

func (m *ContainerOperatingReply) GetErr() error1.ContainerIdOperating {
	if m != nil {
		return m.Err
	}
	return error1.ContainerIdOperating_CONTAINER_OPERATING_SUCCESS
}

func (m *ContainerOperatingReply) GetContainerInfo() []*ContainerOperatingReply_ContainerInfo {
	if m != nil {
		return m.ContainerInfo
	}
	return nil
}

type ContainerOperatingReply_ContainerInfo struct {
	ContainerId          string               `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	OwnedFactoryId       rs.FactoryID         `protobuf:"varint,2,opt,name=owned_factory_id,json=ownedFactoryId,proto3,enum=proto.dm.rs.FactoryID" json:"owned_factory_id,omitempty"`
	OwnedDepartmentId    string               `protobuf:"bytes,3,opt,name=owned_department_id,json=ownedDepartmentId,proto3" json:"owned_department_id,omitempty"`
	Status               code.ContainerStatus `protobuf:"varint,4,opt,name=status,proto3,enum=proto.mes.code.ContainerStatus" json:"status,omitempty"`
	ContainerType        container.Type       `protobuf:"varint,5,opt,name=container_type,json=containerType,proto3,enum=proto.dm.rs.container.Type" json:"container_type,omitempty"`
	UpdateAt             string               `protobuf:"bytes,6,opt,name=update_at,json=updateAt,proto3" json:"update_at,omitempty"`
	UpdateBy             string               `protobuf:"bytes,7,opt,name=update_by,json=updateBy,proto3" json:"update_by,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ContainerOperatingReply_ContainerInfo) Reset()         { *m = ContainerOperatingReply_ContainerInfo{} }
func (m *ContainerOperatingReply_ContainerInfo) String() string { return proto.CompactTextString(m) }
func (*ContainerOperatingReply_ContainerInfo) ProtoMessage()    {}
func (*ContainerOperatingReply_ContainerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_044c5730faf9ff1e, []int{1, 0}
}

func (m *ContainerOperatingReply_ContainerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContainerOperatingReply_ContainerInfo.Unmarshal(m, b)
}
func (m *ContainerOperatingReply_ContainerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContainerOperatingReply_ContainerInfo.Marshal(b, m, deterministic)
}
func (m *ContainerOperatingReply_ContainerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContainerOperatingReply_ContainerInfo.Merge(m, src)
}
func (m *ContainerOperatingReply_ContainerInfo) XXX_Size() int {
	return xxx_messageInfo_ContainerOperatingReply_ContainerInfo.Size(m)
}
func (m *ContainerOperatingReply_ContainerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ContainerOperatingReply_ContainerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ContainerOperatingReply_ContainerInfo proto.InternalMessageInfo

func (m *ContainerOperatingReply_ContainerInfo) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

func (m *ContainerOperatingReply_ContainerInfo) GetOwnedFactoryId() rs.FactoryID {
	if m != nil {
		return m.OwnedFactoryId
	}
	return rs.FactoryID_FACTORY_UNSPECIFIED
}

func (m *ContainerOperatingReply_ContainerInfo) GetOwnedDepartmentId() string {
	if m != nil {
		return m.OwnedDepartmentId
	}
	return ""
}

func (m *ContainerOperatingReply_ContainerInfo) GetStatus() code.ContainerStatus {
	if m != nil {
		return m.Status
	}
	return code.ContainerStatus_CONTAINER_STATUS_UNSPECIFIED
}

func (m *ContainerOperatingReply_ContainerInfo) GetContainerType() container.Type {
	if m != nil {
		return m.ContainerType
	}
	return container.Type_CONTAINER_TYPE_UNSPECIFIED
}

func (m *ContainerOperatingReply_ContainerInfo) GetUpdateAt() string {
	if m != nil {
		return m.UpdateAt
	}
	return ""
}

func (m *ContainerOperatingReply_ContainerInfo) GetUpdateBy() string {
	if m != nil {
		return m.UpdateBy
	}
	return ""
}

func init() {
	proto.RegisterType((*ContainerOperatingRequest)(nil), "proto.mes.ContainerOperatingRequest")
	proto.RegisterType((*ContainerOperatingReply)(nil), "proto.mes.ContainerOperatingReply")
	proto.RegisterType((*ContainerOperatingReply_ContainerInfo)(nil), "proto.mes.ContainerOperatingReply.ContainerInfo")
}

func init() { proto.RegisterFile("container_operating.proto", fileDescriptor_044c5730faf9ff1e) }

var fileDescriptor_044c5730faf9ff1e = []byte{
	// 473 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x5d, 0x8b, 0xd3, 0x40,
	0x14, 0xa5, 0x4d, 0xb7, 0xda, 0xa9, 0x5b, 0x74, 0x04, 0x37, 0xdb, 0x45, 0xac, 0x0b, 0x42, 0xf1,
	0x61, 0x22, 0x15, 0xd9, 0x17, 0x11, 0xad, 0xcb, 0x42, 0x1e, 0x44, 0x88, 0xe2, 0x83, 0x2f, 0x65,
	0x9a, 0xb9, 0x2d, 0xc1, 0xcc, 0x4c, 0x9c, 0x99, 0xb8, 0xe4, 0x2f, 0x08, 0xfe, 0x42, 0xff, 0x8c,
	0xe4, 0xa6, 0x4d, 0x9a, 0xfa, 0x09, 0xf5, 0x29, 0x99, 0x39, 0xe7, 0x9e, 0x7b, 0xe6, 0x9e, 0x49,
	0xc8, 0x69, 0xac, 0x95, 0xe3, 0x89, 0x02, 0xb3, 0xd0, 0x19, 0x18, 0xee, 0x12, 0xb5, 0x66, 0x99,
	0xd1, 0x4e, 0xd3, 0x01, 0x3e, 0x98, 0x04, 0x3b, 0x1e, 0xe3, 0x6b, 0x20, 0xc1, 0x06, 0xb1, 0x16,
	0x10, 0x80, 0xca, 0xa5, 0xad, 0x68, 0xe3, 0xc9, 0x3e, 0x66, 0x8c, 0x36, 0x2d, 0xc6, 0x49, 0xc5,
	0x10, 0x32, 0x30, 0xb6, 0x05, 0x3c, 0xda, 0x05, 0x6a, 0x23, 0x48, 0x59, 0xb8, 0x22, 0x83, 0x8a,
	0x76, 0xfe, 0xd5, 0x23, 0xa7, 0xaf, 0xb7, 0xe8, 0xdb, 0xad, 0xcb, 0x08, 0x3e, 0xe7, 0x60, 0x1d,
	0x7d, 0x41, 0x86, 0x3c, 0x76, 0x89, 0x56, 0x58, 0xe2, 0x77, 0x26, 0x9d, 0xe9, 0x68, 0x76, 0x9f,
	0xd5, 0xe6, 0x59, 0xe9, 0x8a, 0x5d, 0xe5, 0x0a, 0x49, 0x6f, 0xb4, 0x80, 0x34, 0x22, 0x55, 0xc5,
	0xfb, 0x22, 0x03, 0xfa, 0x90, 0xdc, 0x6a, 0x66, 0x90, 0x08, 0xbf, 0x3b, 0xe9, 0x4c, 0x07, 0xd1,
	0xb0, 0xde, 0x0b, 0x05, 0x7d, 0x49, 0x6e, 0xeb, 0x6b, 0x05, 0x62, 0xb1, 0xe2, 0xb1, 0xd3, 0xa6,
	0x28, 0x69, 0x1e, 0xf6, 0xb9, 0xb7, 0xe9, 0x23, 0x24, 0x33, 0x96, 0x5d, 0x55, 0x70, 0x78, 0x19,
	0x8d, 0x90, 0xbf, 0x5d, 0x0b, 0xca, 0xc8, 0xdd, 0x4a, 0x41, 0x40, 0xc6, 0x8d, 0x93, 0xa0, 0x5c,
	0x29, 0xd2, 0xc3, 0x5e, 0x77, 0x10, 0xba, 0xac, 0x91, 0x50, 0xd0, 0x0b, 0xd2, 0xb7, 0x8e, 0xbb,
	0xdc, 0xfa, 0x47, 0xd8, 0xe7, 0xc1, 0xfe, 0x79, 0xea, 0x79, 0xbc, 0x43, 0x5a, 0xb4, 0xa1, 0xd3,
	0x39, 0x19, 0x35, 0xa7, 0xc1, 0x81, 0xf4, 0x51, 0xe0, 0xac, 0x65, 0xb4, 0xa6, 0xb0, 0x72, 0x04,
	0xd1, 0x71, 0xbd, 0xc6, 0x89, 0x9c, 0x91, 0x41, 0x9e, 0x09, 0xee, 0x60, 0xb1, 0x2c, 0xfc, 0x1b,
	0x68, 0xf1, 0x66, 0xb5, 0x31, 0x2f, 0xce, 0xbf, 0xf5, 0xc8, 0xc9, 0xaf, 0xc2, 0xc8, 0xd2, 0x82,
	0x3e, 0x27, 0x1e, 0x18, 0xb3, 0x89, 0xe0, 0xf1, 0xbe, 0x65, 0xbc, 0x18, 0x8d, 0xf1, 0x50, 0x34,
	0xd5, 0x65, 0x19, 0xfd, 0x40, 0x1a, 0x1f, 0xa1, 0x5a, 0x69, 0xbf, 0x3b, 0xf1, 0xa6, 0xc3, 0xd9,
	0x93, 0x1d, 0x9d, 0xdf, 0x34, 0xde, 0x11, 0x55, 0x2b, 0x1d, 0xb5, 0x65, 0xc6, 0xdf, 0xbb, 0xe4,
	0xb8, 0x45, 0xf8, 0x29, 0xf2, 0xce, 0xbf, 0x45, 0xde, 0xfd, 0x1f, 0x91, 0x7b, 0x7f, 0x8f, 0xbc,
	0x77, 0x68, 0xe4, 0x47, 0x07, 0x44, 0xce, 0x1d, 0xde, 0x98, 0x3a, 0xf2, 0x57, 0xee, 0x8f, 0xf7,
	0x61, 0x7e, 0xf1, 0xf1, 0xd9, 0x3a, 0x71, 0x29, 0x5f, 0xb2, 0x4f, 0xa0, 0x04, 0x67, 0xb1, 0x96,
	0xcc, 0x5d, 0x07, 0xb8, 0x08, 0x62, 0x2d, 0xa5, 0x56, 0x36, 0xf8, 0x32, 0x0b, 0xaa, 0x4f, 0x7d,
	0xad, 0x53, 0xae, 0xd6, 0xe5, 0xcf, 0x62, 0xd9, 0xc7, 0x9d, 0xa7, 0x3f, 0x02, 0x00, 0x00, 0xff,
	0xff, 0xca, 0x8a, 0x17, 0x1b, 0x82, 0x04, 0x00, 0x00,
}
