// Code generated by protoc-gen-go. DO NOT EDIT.
// source: equipment_operating.proto

package mes

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	rs "gitlab.kenda.com.tw/kenda/commons/v2/proto/golang/dm/rs"
	code "gitlab.kenda.com.tw/kenda/commons/v2/proto/golang/mes/code"
	error1 "gitlab.kenda.com.tw/kenda/commons/v2/proto/golang/mes/code/error"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EquipmentOperatingRequest struct {
	Action            code.FunctionModel `protobuf:"varint,1,opt,name=action,proto3,enum=proto.mes.code.FunctionModel" json:"action,omitempty"`
	EquipmentId       string             `protobuf:"bytes,2,opt,name=equipment_id,json=equipmentId,proto3" json:"equipment_id,omitempty"`
	OwnedFactoryId    rs.FactoryID       `protobuf:"varint,3,opt,name=owned_factory_id,json=ownedFactoryId,proto3,enum=proto.dm.rs.FactoryID" json:"owned_factory_id,omitempty"`
	OwnedDepartmentId string             `protobuf:"bytes,4,opt,name=owned_department_id,json=ownedDepartmentId,proto3" json:"owned_department_id,omitempty"`
	// TODO: remove this in feature
	BayId       string `protobuf:"bytes,5,opt,name=bay_id,json=bayId,proto3" json:"bay_id,omitempty"`
	Description string `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Volume      string `protobuf:"bytes,7,opt,name=volume,proto3" json:"volume,omitempty"`
	// here are product type values split by `,`
	ProductTypes         string   `protobuf:"bytes,8,opt,name=product_types,json=productTypes,proto3" json:"product_types,omitempty"`
	UpdateBy             string   `protobuf:"bytes,9,opt,name=update_by,json=updateBy,proto3" json:"update_by,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EquipmentOperatingRequest) Reset()         { *m = EquipmentOperatingRequest{} }
func (m *EquipmentOperatingRequest) String() string { return proto.CompactTextString(m) }
func (*EquipmentOperatingRequest) ProtoMessage()    {}
func (*EquipmentOperatingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d5334bd710aa8ad, []int{0}
}

func (m *EquipmentOperatingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EquipmentOperatingRequest.Unmarshal(m, b)
}
func (m *EquipmentOperatingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EquipmentOperatingRequest.Marshal(b, m, deterministic)
}
func (m *EquipmentOperatingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EquipmentOperatingRequest.Merge(m, src)
}
func (m *EquipmentOperatingRequest) XXX_Size() int {
	return xxx_messageInfo_EquipmentOperatingRequest.Size(m)
}
func (m *EquipmentOperatingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EquipmentOperatingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EquipmentOperatingRequest proto.InternalMessageInfo

func (m *EquipmentOperatingRequest) GetAction() code.FunctionModel {
	if m != nil {
		return m.Action
	}
	return code.FunctionModel_FUNCTION_MODEL_UNSPECIFIED
}

func (m *EquipmentOperatingRequest) GetEquipmentId() string {
	if m != nil {
		return m.EquipmentId
	}
	return ""
}

func (m *EquipmentOperatingRequest) GetOwnedFactoryId() rs.FactoryID {
	if m != nil {
		return m.OwnedFactoryId
	}
	return rs.FactoryID_FACTORY_UNSPECIFIED
}

func (m *EquipmentOperatingRequest) GetOwnedDepartmentId() string {
	if m != nil {
		return m.OwnedDepartmentId
	}
	return ""
}

func (m *EquipmentOperatingRequest) GetBayId() string {
	if m != nil {
		return m.BayId
	}
	return ""
}

func (m *EquipmentOperatingRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *EquipmentOperatingRequest) GetVolume() string {
	if m != nil {
		return m.Volume
	}
	return ""
}

func (m *EquipmentOperatingRequest) GetProductTypes() string {
	if m != nil {
		return m.ProductTypes
	}
	return ""
}

func (m *EquipmentOperatingRequest) GetUpdateBy() string {
	if m != nil {
		return m.UpdateBy
	}
	return ""
}

type EquipmentOperatingReply struct {
	Err                  error1.EquipmentOperating            `protobuf:"varint,1,opt,name=err,proto3,enum=proto.mes.code.error.EquipmentOperating" json:"err,omitempty"`
	Equipments           []*EquipmentOperatingReply_Equipment `protobuf:"bytes,2,rep,name=equipments,proto3" json:"equipments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *EquipmentOperatingReply) Reset()         { *m = EquipmentOperatingReply{} }
func (m *EquipmentOperatingReply) String() string { return proto.CompactTextString(m) }
func (*EquipmentOperatingReply) ProtoMessage()    {}
func (*EquipmentOperatingReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d5334bd710aa8ad, []int{1}
}

func (m *EquipmentOperatingReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EquipmentOperatingReply.Unmarshal(m, b)
}
func (m *EquipmentOperatingReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EquipmentOperatingReply.Marshal(b, m, deterministic)
}
func (m *EquipmentOperatingReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EquipmentOperatingReply.Merge(m, src)
}
func (m *EquipmentOperatingReply) XXX_Size() int {
	return xxx_messageInfo_EquipmentOperatingReply.Size(m)
}
func (m *EquipmentOperatingReply) XXX_DiscardUnknown() {
	xxx_messageInfo_EquipmentOperatingReply.DiscardUnknown(m)
}

var xxx_messageInfo_EquipmentOperatingReply proto.InternalMessageInfo

func (m *EquipmentOperatingReply) GetErr() error1.EquipmentOperating {
	if m != nil {
		return m.Err
	}
	return error1.EquipmentOperating_EQUIPMENT_OPERATING_SUCCESS
}

func (m *EquipmentOperatingReply) GetEquipments() []*EquipmentOperatingReply_Equipment {
	if m != nil {
		return m.Equipments
	}
	return nil
}

type EquipmentOperatingReply_Equipment struct {
	Id                string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnedFactoryId    rs.FactoryID `protobuf:"varint,2,opt,name=owned_factory_id,json=ownedFactoryId,proto3,enum=proto.dm.rs.FactoryID" json:"owned_factory_id,omitempty"`
	OwnedDepartmentId string       `protobuf:"bytes,3,opt,name=owned_department_id,json=ownedDepartmentId,proto3" json:"owned_department_id,omitempty"`
	// TODO: remove this in feature
	BayId       string `protobuf:"bytes,4,opt,name=bay_id,json=bayId,proto3" json:"bay_id,omitempty"`
	Description string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Volume      string `protobuf:"bytes,6,opt,name=volume,proto3" json:"volume,omitempty"`
	// here are product type values split by `,`
	ProductTypes         string   `protobuf:"bytes,7,opt,name=product_types,json=productTypes,proto3" json:"product_types,omitempty"`
	UpdateBy             string   `protobuf:"bytes,8,opt,name=update_by,json=updateBy,proto3" json:"update_by,omitempty"`
	UpdateAt             string   `protobuf:"bytes,9,opt,name=update_at,json=updateAt,proto3" json:"update_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EquipmentOperatingReply_Equipment) Reset()         { *m = EquipmentOperatingReply_Equipment{} }
func (m *EquipmentOperatingReply_Equipment) String() string { return proto.CompactTextString(m) }
func (*EquipmentOperatingReply_Equipment) ProtoMessage()    {}
func (*EquipmentOperatingReply_Equipment) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d5334bd710aa8ad, []int{1, 0}
}

func (m *EquipmentOperatingReply_Equipment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EquipmentOperatingReply_Equipment.Unmarshal(m, b)
}
func (m *EquipmentOperatingReply_Equipment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EquipmentOperatingReply_Equipment.Marshal(b, m, deterministic)
}
func (m *EquipmentOperatingReply_Equipment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EquipmentOperatingReply_Equipment.Merge(m, src)
}
func (m *EquipmentOperatingReply_Equipment) XXX_Size() int {
	return xxx_messageInfo_EquipmentOperatingReply_Equipment.Size(m)
}
func (m *EquipmentOperatingReply_Equipment) XXX_DiscardUnknown() {
	xxx_messageInfo_EquipmentOperatingReply_Equipment.DiscardUnknown(m)
}

var xxx_messageInfo_EquipmentOperatingReply_Equipment proto.InternalMessageInfo

func (m *EquipmentOperatingReply_Equipment) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *EquipmentOperatingReply_Equipment) GetOwnedFactoryId() rs.FactoryID {
	if m != nil {
		return m.OwnedFactoryId
	}
	return rs.FactoryID_FACTORY_UNSPECIFIED
}

func (m *EquipmentOperatingReply_Equipment) GetOwnedDepartmentId() string {
	if m != nil {
		return m.OwnedDepartmentId
	}
	return ""
}

func (m *EquipmentOperatingReply_Equipment) GetBayId() string {
	if m != nil {
		return m.BayId
	}
	return ""
}

func (m *EquipmentOperatingReply_Equipment) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *EquipmentOperatingReply_Equipment) GetVolume() string {
	if m != nil {
		return m.Volume
	}
	return ""
}

func (m *EquipmentOperatingReply_Equipment) GetProductTypes() string {
	if m != nil {
		return m.ProductTypes
	}
	return ""
}

func (m *EquipmentOperatingReply_Equipment) GetUpdateBy() string {
	if m != nil {
		return m.UpdateBy
	}
	return ""
}

func (m *EquipmentOperatingReply_Equipment) GetUpdateAt() string {
	if m != nil {
		return m.UpdateAt
	}
	return ""
}

func init() {
	proto.RegisterType((*EquipmentOperatingRequest)(nil), "proto.mes.EquipmentOperatingRequest")
	proto.RegisterType((*EquipmentOperatingReply)(nil), "proto.mes.EquipmentOperatingReply")
	proto.RegisterType((*EquipmentOperatingReply_Equipment)(nil), "proto.mes.EquipmentOperatingReply.Equipment")
}

func init() { proto.RegisterFile("equipment_operating.proto", fileDescriptor_2d5334bd710aa8ad) }

var fileDescriptor_2d5334bd710aa8ad = []byte{
	// 472 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0x5d, 0x6b, 0xdb, 0x30,
	0x14, 0x25, 0x4e, 0xe3, 0xc6, 0x4a, 0x17, 0x36, 0x8d, 0xb5, 0x6e, 0xc6, 0xc0, 0xeb, 0x5e, 0xf2,
	0x30, 0x64, 0xc8, 0x28, 0x83, 0x3d, 0x6d, 0xa5, 0x2b, 0x04, 0x36, 0x06, 0x66, 0x4f, 0x7b, 0x09,
	0xb2, 0x75, 0x17, 0xcc, 0xac, 0x8f, 0x4a, 0x72, 0x8b, 0x7f, 0xdc, 0x7e, 0xcd, 0xfe, 0xc5, 0x9e,
	0x86, 0x65, 0xc7, 0x75, 0x4a, 0x96, 0xbe, 0xf4, 0xc9, 0xd6, 0x39, 0xe7, 0xde, 0x73, 0x75, 0x0f,
	0x42, 0xa7, 0x70, 0x5d, 0xe6, 0x8a, 0x83, 0xb0, 0x2b, 0xa9, 0x40, 0x53, 0x9b, 0x8b, 0x35, 0x51,
	0x5a, 0x5a, 0x89, 0x03, 0xf7, 0x21, 0x1c, 0xcc, 0x6c, 0xe6, 0x7e, 0x63, 0x0e, 0x26, 0xce, 0x24,
	0x83, 0x18, 0x44, 0xc9, 0x4d, 0x23, 0x9b, 0x45, 0xf7, 0x39, 0xad, 0xa5, 0xde, 0x52, 0x9c, 0x34,
	0x0a, 0xc6, 0x63, 0x6d, 0xfa, 0xc4, 0xd9, 0x5f, 0x0f, 0x9d, 0x7e, 0xde, 0xf8, 0x7f, 0xdb, 0xd8,
	0x27, 0x70, 0x5d, 0x82, 0xb1, 0xf8, 0x1c, 0xf9, 0x34, 0xb3, 0xb9, 0x14, 0xe1, 0x20, 0x1a, 0xcc,
	0xa7, 0x8b, 0x57, 0xa4, 0x1b, 0x88, 0xd4, 0x4e, 0xe4, 0xaa, 0x14, 0x8e, 0xff, 0x2a, 0x19, 0x14,
	0x49, 0x2b, 0xc6, 0xaf, 0xd1, 0xd1, 0xdd, 0x9d, 0x72, 0x16, 0x7a, 0xd1, 0x60, 0x1e, 0x24, 0x93,
	0x0e, 0x5b, 0x32, 0xfc, 0x11, 0x3d, 0x95, 0xb7, 0x02, 0xd8, 0xea, 0x27, 0xcd, 0xac, 0xd4, 0x55,
	0x2d, 0x1b, 0x3a, 0x8f, 0xe3, 0xd6, 0x83, 0x71, 0xa2, 0x0d, 0xb9, 0x6a, 0xe8, 0xe5, 0x65, 0x32,
	0x75, 0xfa, 0xcd, 0x99, 0x61, 0x82, 0x9e, 0x37, 0x1d, 0x18, 0x28, 0xaa, 0xed, 0xc6, 0xeb, 0xc0,
	0x79, 0x3d, 0x73, 0xd4, 0x65, 0xc7, 0x2c, 0x19, 0x7e, 0x81, 0xfc, 0x94, 0x3a, 0x9f, 0x91, 0x93,
	0x8c, 0x52, 0x5a, 0xb7, 0x89, 0xd0, 0x84, 0x81, 0xc9, 0x74, 0xae, 0xdc, 0x3d, 0xfd, 0x66, 0xd4,
	0x1e, 0x84, 0x8f, 0x91, 0x7f, 0x23, 0x8b, 0x92, 0x43, 0x78, 0xe8, 0xc8, 0xf6, 0x84, 0xdf, 0xa0,
	0x27, 0x4a, 0x4b, 0x56, 0x66, 0x76, 0x65, 0x2b, 0x05, 0x26, 0x1c, 0x3b, 0xfa, 0xa8, 0x05, 0xbf,
	0xd7, 0x18, 0x7e, 0x89, 0x82, 0x52, 0x31, 0x6a, 0x61, 0x95, 0x56, 0x61, 0xe0, 0x04, 0xe3, 0x06,
	0xb8, 0xa8, 0xce, 0xfe, 0x0c, 0xd1, 0xc9, 0xae, 0xe5, 0xab, 0xa2, 0xc2, 0x1f, 0xd0, 0x10, 0xb4,
	0x6e, 0xf7, 0x3e, 0xbf, 0xbf, 0x77, 0x97, 0x30, 0xd9, 0x51, 0x5b, 0x17, 0xe1, 0x2f, 0x08, 0x75,
	0xbb, 0x36, 0xa1, 0x17, 0x0d, 0xe7, 0x93, 0xc5, 0xdb, 0x5e, 0x8b, 0xff, 0x78, 0xde, 0xe1, 0x49,
	0xaf, 0x7e, 0xf6, 0xdb, 0x43, 0x41, 0xc7, 0xe0, 0x29, 0xf2, 0x72, 0xe6, 0xc6, 0x0a, 0x12, 0x2f,
	0xdf, 0x1d, 0xa4, 0xf7, 0x18, 0x41, 0x0e, 0x1f, 0x0e, 0xf2, 0x60, 0x4f, 0x90, 0xa3, 0x7d, 0x41,
	0xfa, 0xfb, 0x83, 0x3c, 0x7c, 0x28, 0xc8, 0xf1, 0x76, 0x90, 0x3d, 0x92, 0xda, 0xed, 0x94, 0x3f,
	0xd9, 0x8b, 0xf7, 0x3f, 0xce, 0xd7, 0xb9, 0x2d, 0x68, 0x4a, 0x7e, 0x81, 0x60, 0x94, 0x64, 0x92,
	0x13, 0x7b, 0x1b, 0xbb, 0x43, 0x9c, 0x49, 0xce, 0xa5, 0x30, 0xf1, 0xcd, 0x22, 0x6e, 0x9e, 0xe8,
	0x5a, 0x16, 0x54, 0xac, 0xeb, 0xb7, 0x9c, 0xfa, 0x0e, 0x79, 0xf7, 0x2f, 0x00, 0x00, 0xff, 0xff,
	0x15, 0x72, 0xeb, 0x81, 0x21, 0x04, 0x00, 0x00,
}
