// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mp_service.proto

package mes

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 依生胎條碼取得MP配方ID請求
type GetRecipeIDByBarcodeRequest struct {
	// 生胎條碼
	Barcode string `protobuf:"bytes,1,opt,name=barcode,proto3" json:"barcode,omitempty"`
	// 設備ID
	EquipmentId          string   `protobuf:"bytes,2,opt,name=equipment_id,json=equipmentId,proto3" json:"equipment_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRecipeIDByBarcodeRequest) Reset()         { *m = GetRecipeIDByBarcodeRequest{} }
func (m *GetRecipeIDByBarcodeRequest) String() string { return proto.CompactTextString(m) }
func (*GetRecipeIDByBarcodeRequest) ProtoMessage()    {}
func (*GetRecipeIDByBarcodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea9b69c11417c3cf, []int{0}
}

func (m *GetRecipeIDByBarcodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRecipeIDByBarcodeRequest.Unmarshal(m, b)
}
func (m *GetRecipeIDByBarcodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRecipeIDByBarcodeRequest.Marshal(b, m, deterministic)
}
func (m *GetRecipeIDByBarcodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRecipeIDByBarcodeRequest.Merge(m, src)
}
func (m *GetRecipeIDByBarcodeRequest) XXX_Size() int {
	return xxx_messageInfo_GetRecipeIDByBarcodeRequest.Size(m)
}
func (m *GetRecipeIDByBarcodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRecipeIDByBarcodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRecipeIDByBarcodeRequest proto.InternalMessageInfo

func (m *GetRecipeIDByBarcodeRequest) GetBarcode() string {
	if m != nil {
		return m.Barcode
	}
	return ""
}

func (m *GetRecipeIDByBarcodeRequest) GetEquipmentId() string {
	if m != nil {
		return m.EquipmentId
	}
	return ""
}

// 依生胎條碼取得MP配方ID回應
type GetRecipeIDByBarcodeReply struct {
	// 配合表ID
	RecipeId             string   `protobuf:"bytes,1,opt,name=recipe_id,json=recipeId,proto3" json:"recipe_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRecipeIDByBarcodeReply) Reset()         { *m = GetRecipeIDByBarcodeReply{} }
func (m *GetRecipeIDByBarcodeReply) String() string { return proto.CompactTextString(m) }
func (*GetRecipeIDByBarcodeReply) ProtoMessage()    {}
func (*GetRecipeIDByBarcodeReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea9b69c11417c3cf, []int{1}
}

func (m *GetRecipeIDByBarcodeReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRecipeIDByBarcodeReply.Unmarshal(m, b)
}
func (m *GetRecipeIDByBarcodeReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRecipeIDByBarcodeReply.Marshal(b, m, deterministic)
}
func (m *GetRecipeIDByBarcodeReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRecipeIDByBarcodeReply.Merge(m, src)
}
func (m *GetRecipeIDByBarcodeReply) XXX_Size() int {
	return xxx_messageInfo_GetRecipeIDByBarcodeReply.Size(m)
}
func (m *GetRecipeIDByBarcodeReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRecipeIDByBarcodeReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetRecipeIDByBarcodeReply proto.InternalMessageInfo

func (m *GetRecipeIDByBarcodeReply) GetRecipeId() string {
	if m != nil {
		return m.RecipeId
	}
	return ""
}

// 取得MP配方明細請求
type GetRecipeForMpRequest struct {
	// 配合表ID
	RecipeId string `protobuf:"bytes,1,opt,name=recipe_id,json=recipeId,proto3" json:"recipe_id,omitempty"`
	// 設備ID
	EquipmentId          string   `protobuf:"bytes,2,opt,name=equipment_id,json=equipmentId,proto3" json:"equipment_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRecipeForMpRequest) Reset()         { *m = GetRecipeForMpRequest{} }
func (m *GetRecipeForMpRequest) String() string { return proto.CompactTextString(m) }
func (*GetRecipeForMpRequest) ProtoMessage()    {}
func (*GetRecipeForMpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea9b69c11417c3cf, []int{2}
}

func (m *GetRecipeForMpRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRecipeForMpRequest.Unmarshal(m, b)
}
func (m *GetRecipeForMpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRecipeForMpRequest.Marshal(b, m, deterministic)
}
func (m *GetRecipeForMpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRecipeForMpRequest.Merge(m, src)
}
func (m *GetRecipeForMpRequest) XXX_Size() int {
	return xxx_messageInfo_GetRecipeForMpRequest.Size(m)
}
func (m *GetRecipeForMpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRecipeForMpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRecipeForMpRequest proto.InternalMessageInfo

func (m *GetRecipeForMpRequest) GetRecipeId() string {
	if m != nil {
		return m.RecipeId
	}
	return ""
}

func (m *GetRecipeForMpRequest) GetEquipmentId() string {
	if m != nil {
		return m.EquipmentId
	}
	return ""
}

// 取得MP配方明細回應
type GetRecipeForMpReply struct {
	// 配方參數清單
	Parameters           []*GetRecipeForMpReply_Parameter `protobuf:"bytes,1,rep,name=parameters,proto3" json:"parameters,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *GetRecipeForMpReply) Reset()         { *m = GetRecipeForMpReply{} }
func (m *GetRecipeForMpReply) String() string { return proto.CompactTextString(m) }
func (*GetRecipeForMpReply) ProtoMessage()    {}
func (*GetRecipeForMpReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea9b69c11417c3cf, []int{3}
}

func (m *GetRecipeForMpReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRecipeForMpReply.Unmarshal(m, b)
}
func (m *GetRecipeForMpReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRecipeForMpReply.Marshal(b, m, deterministic)
}
func (m *GetRecipeForMpReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRecipeForMpReply.Merge(m, src)
}
func (m *GetRecipeForMpReply) XXX_Size() int {
	return xxx_messageInfo_GetRecipeForMpReply.Size(m)
}
func (m *GetRecipeForMpReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRecipeForMpReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetRecipeForMpReply proto.InternalMessageInfo

func (m *GetRecipeForMpReply) GetParameters() []*GetRecipeForMpReply_Parameter {
	if m != nil {
		return m.Parameters
	}
	return nil
}

// 參數
type GetRecipeForMpReply_Parameter struct {
	// 參數ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 參數描述
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// 最大值
	Maximum float32 `protobuf:"fixed32,3,opt,name=maximum,proto3" json:"maximum,omitempty"`
	// 標準值
	Standard float32 `protobuf:"fixed32,4,opt,name=standard,proto3" json:"standard,omitempty"`
	// 最小值
	Minimum float32 `protobuf:"fixed32,5,opt,name=minimum,proto3" json:"minimum,omitempty"`
	// 計量單位
	Unit                 string   `protobuf:"bytes,6,opt,name=unit,proto3" json:"unit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRecipeForMpReply_Parameter) Reset()         { *m = GetRecipeForMpReply_Parameter{} }
func (m *GetRecipeForMpReply_Parameter) String() string { return proto.CompactTextString(m) }
func (*GetRecipeForMpReply_Parameter) ProtoMessage()    {}
func (*GetRecipeForMpReply_Parameter) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea9b69c11417c3cf, []int{3, 0}
}

func (m *GetRecipeForMpReply_Parameter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRecipeForMpReply_Parameter.Unmarshal(m, b)
}
func (m *GetRecipeForMpReply_Parameter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRecipeForMpReply_Parameter.Marshal(b, m, deterministic)
}
func (m *GetRecipeForMpReply_Parameter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRecipeForMpReply_Parameter.Merge(m, src)
}
func (m *GetRecipeForMpReply_Parameter) XXX_Size() int {
	return xxx_messageInfo_GetRecipeForMpReply_Parameter.Size(m)
}
func (m *GetRecipeForMpReply_Parameter) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRecipeForMpReply_Parameter.DiscardUnknown(m)
}

var xxx_messageInfo_GetRecipeForMpReply_Parameter proto.InternalMessageInfo

func (m *GetRecipeForMpReply_Parameter) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetRecipeForMpReply_Parameter) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *GetRecipeForMpReply_Parameter) GetMaximum() float32 {
	if m != nil {
		return m.Maximum
	}
	return 0
}

func (m *GetRecipeForMpReply_Parameter) GetStandard() float32 {
	if m != nil {
		return m.Standard
	}
	return 0
}

func (m *GetRecipeForMpReply_Parameter) GetMinimum() float32 {
	if m != nil {
		return m.Minimum
	}
	return 0
}

func (m *GetRecipeForMpReply_Parameter) GetUnit() string {
	if m != nil {
		return m.Unit
	}
	return ""
}

// 透過生胎條碼確認是否為不良品請求
type IsRejectsRequest struct {
	// 生胎條碼
	Barcode              string   `protobuf:"bytes,1,opt,name=barcode,proto3" json:"barcode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsRejectsRequest) Reset()         { *m = IsRejectsRequest{} }
func (m *IsRejectsRequest) String() string { return proto.CompactTextString(m) }
func (*IsRejectsRequest) ProtoMessage()    {}
func (*IsRejectsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea9b69c11417c3cf, []int{4}
}

func (m *IsRejectsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsRejectsRequest.Unmarshal(m, b)
}
func (m *IsRejectsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsRejectsRequest.Marshal(b, m, deterministic)
}
func (m *IsRejectsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsRejectsRequest.Merge(m, src)
}
func (m *IsRejectsRequest) XXX_Size() int {
	return xxx_messageInfo_IsRejectsRequest.Size(m)
}
func (m *IsRejectsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IsRejectsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IsRejectsRequest proto.InternalMessageInfo

func (m *IsRejectsRequest) GetBarcode() string {
	if m != nil {
		return m.Barcode
	}
	return ""
}

// 透過生胎條碼確認是否為不良品回應
type IsRejectsReply struct {
	// 是否為不良品 true=不良
	IsRejects            bool     `protobuf:"varint,1,opt,name=is_rejects,json=isRejects,proto3" json:"is_rejects,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsRejectsReply) Reset()         { *m = IsRejectsReply{} }
func (m *IsRejectsReply) String() string { return proto.CompactTextString(m) }
func (*IsRejectsReply) ProtoMessage()    {}
func (*IsRejectsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea9b69c11417c3cf, []int{5}
}

func (m *IsRejectsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsRejectsReply.Unmarshal(m, b)
}
func (m *IsRejectsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsRejectsReply.Marshal(b, m, deterministic)
}
func (m *IsRejectsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsRejectsReply.Merge(m, src)
}
func (m *IsRejectsReply) XXX_Size() int {
	return xxx_messageInfo_IsRejectsReply.Size(m)
}
func (m *IsRejectsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_IsRejectsReply.DiscardUnknown(m)
}

var xxx_messageInfo_IsRejectsReply proto.InternalMessageInfo

func (m *IsRejectsReply) GetIsRejects() bool {
	if m != nil {
		return m.IsRejects
	}
	return false
}

func init() {
	proto.RegisterType((*GetRecipeIDByBarcodeRequest)(nil), "proto.mes.GetRecipeIDByBarcodeRequest")
	proto.RegisterType((*GetRecipeIDByBarcodeReply)(nil), "proto.mes.GetRecipeIDByBarcodeReply")
	proto.RegisterType((*GetRecipeForMpRequest)(nil), "proto.mes.GetRecipeForMpRequest")
	proto.RegisterType((*GetRecipeForMpReply)(nil), "proto.mes.GetRecipeForMpReply")
	proto.RegisterType((*GetRecipeForMpReply_Parameter)(nil), "proto.mes.GetRecipeForMpReply.Parameter")
	proto.RegisterType((*IsRejectsRequest)(nil), "proto.mes.IsRejectsRequest")
	proto.RegisterType((*IsRejectsReply)(nil), "proto.mes.IsRejectsReply")
}

func init() { proto.RegisterFile("mp_service.proto", fileDescriptor_ea9b69c11417c3cf) }

var fileDescriptor_ea9b69c11417c3cf = []byte{
	// 370 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xcf, 0xca, 0xd3, 0x40,
	0x14, 0xc5, 0x49, 0xbe, 0xcf, 0xda, 0xdc, 0x4a, 0x29, 0x23, 0x42, 0x6c, 0x11, 0x62, 0x56, 0x59,
	0xc8, 0x04, 0x2a, 0xa2, 0xeb, 0x22, 0x6a, 0x16, 0x82, 0x64, 0x23, 0x74, 0x53, 0xa6, 0x99, 0x4b,
	0x19, 0xed, 0xfc, 0xe9, 0xcc, 0xa4, 0xda, 0xb5, 0x4f, 0xe2, 0x9b, 0x4a, 0x26, 0x26, 0x14, 0x29,
	0xea, 0x2a, 0x39, 0xe7, 0xde, 0xdf, 0xcd, 0xe1, 0x04, 0x16, 0xd2, 0xec, 0x1c, 0xda, 0xb3, 0x68,
	0x90, 0x1a, 0xab, 0xbd, 0x26, 0x49, 0x78, 0x50, 0x89, 0x2e, 0xdf, 0xc2, 0xea, 0x3d, 0xfa, 0x1a,
	0x1b, 0x61, 0xb0, 0x7a, 0xbb, 0xb9, 0x6c, 0x98, 0x6d, 0x34, 0xc7, 0x1a, 0x4f, 0x2d, 0x3a, 0x4f,
	0x52, 0x78, 0xb8, 0xef, 0x9d, 0x34, 0xca, 0xa2, 0x22, 0xa9, 0x07, 0x49, 0x9e, 0xc3, 0x23, 0x3c,
	0xb5, 0xc2, 0x48, 0x54, 0x7e, 0x27, 0x78, 0x1a, 0x87, 0xf1, 0x6c, 0xf4, 0x2a, 0x9e, 0xbf, 0x81,
	0xa7, 0xb7, 0x6f, 0x9b, 0xe3, 0x85, 0xac, 0x20, 0xb1, 0x61, 0xd2, 0xc1, 0xfd, 0xed, 0x69, 0x6f,
	0x54, 0x3c, 0xff, 0x0c, 0x4f, 0x46, 0xf2, 0x9d, 0xb6, 0x1f, 0xcd, 0x90, 0xe7, 0x6f, 0xd4, 0xff,
	0x44, 0xfa, 0x11, 0xc3, 0xe3, 0x3f, 0x2f, 0x77, 0x69, 0x3e, 0x00, 0x18, 0x66, 0x99, 0x44, 0x8f,
	0xd6, 0xa5, 0x51, 0x76, 0x57, 0xcc, 0xd6, 0x05, 0x1d, 0x6b, 0xa2, 0x37, 0x18, 0xfa, 0x69, 0x00,
	0xea, 0x2b, 0x76, 0xf9, 0x33, 0x82, 0x64, 0x9c, 0x90, 0x39, 0xc4, 0x63, 0xd0, 0x58, 0x70, 0x92,
	0xc1, 0x8c, 0xa3, 0x6b, 0xac, 0x30, 0x5e, 0x68, 0x35, 0x24, 0xbc, 0xb2, 0xba, 0xc6, 0x25, 0xfb,
	0x2e, 0x64, 0x2b, 0xd3, 0xbb, 0x2c, 0x2a, 0xe2, 0x7a, 0x90, 0x64, 0x09, 0x53, 0xe7, 0x99, 0xe2,
	0xcc, 0xf2, 0xf4, 0x3e, 0x8c, 0x46, 0x1d, 0x28, 0xa1, 0x02, 0xf5, 0xe0, 0x37, 0xd5, 0x4b, 0x42,
	0xe0, 0xbe, 0x55, 0xc2, 0xa7, 0x93, 0xf0, 0xa9, 0xf0, 0x9e, 0xbf, 0x80, 0x45, 0xe5, 0x6a, 0xfc,
	0x82, 0x8d, 0x77, 0xff, 0xfc, 0xd3, 0x79, 0x09, 0xf3, 0xab, 0xed, 0xae, 0xad, 0x67, 0x00, 0xc2,
	0xed, 0x6c, 0x6f, 0x85, 0xf5, 0x69, 0x9d, 0x88, 0x61, 0x67, 0xf3, 0x7a, 0xfb, 0xea, 0x20, 0xfc,
	0x91, 0xed, 0xe9, 0x57, 0x54, 0x9c, 0xd1, 0x46, 0x4b, 0xea, 0xbf, 0x95, 0x41, 0x94, 0x8d, 0x96,
	0x52, 0x2b, 0x57, 0x9e, 0xd7, 0x65, 0xa8, 0xb7, 0x3c, 0xe8, 0x23, 0x53, 0x87, 0x52, 0xa2, 0xdb,
	0x4f, 0x82, 0xf3, 0xf2, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x93, 0xc2, 0x64, 0x1f, 0xb2, 0x02,
	0x00, 0x00,
}
