// Code generated by protoc-gen-go. DO NOT EDIT.
// source: worker.proto

package mes

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	error1 "gitlab.kenda.com.tw/kenda/commons/v2/proto/golang/mes/code/error"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 類別 I = login , O = logout
type LoginAndLogoutRequest_Mode int32

const (
	// 登入
	LoginAndLogoutRequest_LOGIN LoginAndLogoutRequest_Mode = 0
	// 登出
	LoginAndLogoutRequest_LOGOUT LoginAndLogoutRequest_Mode = 1
)

var LoginAndLogoutRequest_Mode_name = map[int32]string{
	0: "LOGIN",
	1: "LOGOUT",
}

var LoginAndLogoutRequest_Mode_value = map[string]int32{
	"LOGIN":  0,
	"LOGOUT": 1,
}

func (x LoginAndLogoutRequest_Mode) String() string {
	return proto.EnumName(LoginAndLogoutRequest_Mode_name, int32(x))
}

func (LoginAndLogoutRequest_Mode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e4ff6184b07e587a, []int{0, 0}
}

//登入/登出請求
type LoginAndLogoutRequest struct {
	ActionMode LoginAndLogoutRequest_Mode `protobuf:"varint,1,opt,name=action_mode,json=actionMode,proto3,enum=proto.mes.LoginAndLogoutRequest_Mode" json:"action_mode,omitempty"`
	//作業機台號
	EquipmentId string `protobuf:"bytes,2,opt,name=equipment_id,json=equipmentId,proto3" json:"equipment_id,omitempty"`
	//操作者
	UpdateBy string `protobuf:"bytes,3,opt,name=update_by,json=updateBy,proto3" json:"update_by,omitempty"`
	//工作日
	WorkDate string `protobuf:"bytes,4,opt,name=work_date,json=workDate,proto3" json:"work_date,omitempty"`
	//班別
	Shift string `protobuf:"bytes,5,opt,name=shift,proto3" json:"shift,omitempty"`
	//廠別
	SubCompany string `protobuf:"bytes,6,opt,name=sub_company,json=subCompany,proto3" json:"sub_company,omitempty"`
	//員工工號
	EmployeeNumber       string   `protobuf:"bytes,7,opt,name=employee_number,json=employeeNumber,proto3" json:"employee_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginAndLogoutRequest) Reset()         { *m = LoginAndLogoutRequest{} }
func (m *LoginAndLogoutRequest) String() string { return proto.CompactTextString(m) }
func (*LoginAndLogoutRequest) ProtoMessage()    {}
func (*LoginAndLogoutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4ff6184b07e587a, []int{0}
}

func (m *LoginAndLogoutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginAndLogoutRequest.Unmarshal(m, b)
}
func (m *LoginAndLogoutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginAndLogoutRequest.Marshal(b, m, deterministic)
}
func (m *LoginAndLogoutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginAndLogoutRequest.Merge(m, src)
}
func (m *LoginAndLogoutRequest) XXX_Size() int {
	return xxx_messageInfo_LoginAndLogoutRequest.Size(m)
}
func (m *LoginAndLogoutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginAndLogoutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginAndLogoutRequest proto.InternalMessageInfo

func (m *LoginAndLogoutRequest) GetActionMode() LoginAndLogoutRequest_Mode {
	if m != nil {
		return m.ActionMode
	}
	return LoginAndLogoutRequest_LOGIN
}

func (m *LoginAndLogoutRequest) GetEquipmentId() string {
	if m != nil {
		return m.EquipmentId
	}
	return ""
}

func (m *LoginAndLogoutRequest) GetUpdateBy() string {
	if m != nil {
		return m.UpdateBy
	}
	return ""
}

func (m *LoginAndLogoutRequest) GetWorkDate() string {
	if m != nil {
		return m.WorkDate
	}
	return ""
}

func (m *LoginAndLogoutRequest) GetShift() string {
	if m != nil {
		return m.Shift
	}
	return ""
}

func (m *LoginAndLogoutRequest) GetSubCompany() string {
	if m != nil {
		return m.SubCompany
	}
	return ""
}

func (m *LoginAndLogoutRequest) GetEmployeeNumber() string {
	if m != nil {
		return m.EmployeeNumber
	}
	return ""
}

// 登入登出回應
type LoginAndLogoutReply struct {
	// 錯誤代碼
	Err error1.LoginAndLogout `protobuf:"varint,1,opt,name=err,proto3,enum=proto.mes.code.error.LoginAndLogout" json:"err,omitempty"`
	//職稱 for permission control
	//     select jobtit from permas
	//     this column values is mapping by seccod.codekind = 'KE'
	JobTitle string `protobuf:"bytes,2,opt,name=job_title,json=jobTitle,proto3" json:"job_title,omitempty"`
	// 員工姓名
	EmployeeName string `protobuf:"bytes,3,opt,name=employee_name,json=employeeName,proto3" json:"employee_name,omitempty"`
	// 部門代號
	DepartmentId         string   `protobuf:"bytes,4,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginAndLogoutReply) Reset()         { *m = LoginAndLogoutReply{} }
func (m *LoginAndLogoutReply) String() string { return proto.CompactTextString(m) }
func (*LoginAndLogoutReply) ProtoMessage()    {}
func (*LoginAndLogoutReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4ff6184b07e587a, []int{1}
}

func (m *LoginAndLogoutReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginAndLogoutReply.Unmarshal(m, b)
}
func (m *LoginAndLogoutReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginAndLogoutReply.Marshal(b, m, deterministic)
}
func (m *LoginAndLogoutReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginAndLogoutReply.Merge(m, src)
}
func (m *LoginAndLogoutReply) XXX_Size() int {
	return xxx_messageInfo_LoginAndLogoutReply.Size(m)
}
func (m *LoginAndLogoutReply) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginAndLogoutReply.DiscardUnknown(m)
}

var xxx_messageInfo_LoginAndLogoutReply proto.InternalMessageInfo

func (m *LoginAndLogoutReply) GetErr() error1.LoginAndLogout {
	if m != nil {
		return m.Err
	}
	return error1.LoginAndLogout_LOGIN_AND_LOGOUT_SUCCESS
}

func (m *LoginAndLogoutReply) GetJobTitle() string {
	if m != nil {
		return m.JobTitle
	}
	return ""
}

func (m *LoginAndLogoutReply) GetEmployeeName() string {
	if m != nil {
		return m.EmployeeName
	}
	return ""
}

func (m *LoginAndLogoutReply) GetDepartmentId() string {
	if m != nil {
		return m.DepartmentId
	}
	return ""
}

func init() {
	proto.RegisterEnum("proto.mes.LoginAndLogoutRequest_Mode", LoginAndLogoutRequest_Mode_name, LoginAndLogoutRequest_Mode_value)
	proto.RegisterType((*LoginAndLogoutRequest)(nil), "proto.mes.LoginAndLogoutRequest")
	proto.RegisterType((*LoginAndLogoutReply)(nil), "proto.mes.LoginAndLogoutReply")
}

func init() { proto.RegisterFile("worker.proto", fileDescriptor_e4ff6184b07e587a) }

var fileDescriptor_e4ff6184b07e587a = []byte{
	// 410 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xd1, 0x6f, 0xd3, 0x30,
	0x10, 0xc6, 0xc9, 0xb6, 0x96, 0xf5, 0x5a, 0xc6, 0x64, 0x40, 0x8a, 0x40, 0x88, 0x52, 0x40, 0xec,
	0xc9, 0x91, 0x86, 0x80, 0x67, 0x06, 0x62, 0xaa, 0x54, 0x56, 0xa9, 0x1a, 0x2f, 0xbc, 0x44, 0x4e,
	0x7c, 0x84, 0x6c, 0xb1, 0x2f, 0x73, 0x6c, 0xa6, 0xfc, 0x5f, 0xbc, 0xf1, 0xcf, 0x21, 0xdb, 0x5d,
	0x87, 0xaa, 0x3d, 0xc5, 0xdf, 0xf7, 0xdd, 0x45, 0xbe, 0x9f, 0x0f, 0x26, 0xd7, 0x64, 0x2e, 0xd1,
	0xf0, 0xd6, 0x90, 0x25, 0x36, 0x0a, 0x1f, 0xae, 0xb0, 0x7b, 0x3a, 0x0d, 0xc7, 0x4c, 0x61, 0x97,
	0x95, 0x24, 0x31, 0x43, 0x63, 0xc8, 0x64, 0xa8, 0x9d, 0xea, 0x62, 0xf1, 0xec, 0xef, 0x0e, 0x3c,
	0x59, 0x50, 0x55, 0xeb, 0x4f, 0x5a, 0x2e, 0xa8, 0x22, 0x67, 0x57, 0x78, 0xe5, 0xb0, 0xb3, 0xec,
	0x2b, 0x8c, 0x45, 0x69, 0x6b, 0xd2, 0xb9, 0x22, 0x89, 0x69, 0x32, 0x4d, 0x8e, 0x0e, 0x8e, 0xdf,
	0xf0, 0xcd, 0xcf, 0xf9, 0x9d, 0x6d, 0xfc, 0x1b, 0x49, 0x5c, 0x41, 0xec, 0xf4, 0x67, 0xf6, 0x12,
	0x26, 0x78, 0xe5, 0xea, 0x56, 0xa1, 0xb6, 0x79, 0x2d, 0xd3, 0x9d, 0x69, 0x72, 0x34, 0x5a, 0x8d,
	0x37, 0xde, 0x5c, 0xb2, 0x67, 0x30, 0x72, 0xad, 0x14, 0x16, 0xf3, 0xa2, 0x4f, 0x77, 0x43, 0xbe,
	0x1f, 0x8d, 0x93, 0xde, 0x87, 0x7e, 0xbc, 0xdc, 0xcb, 0x74, 0x2f, 0x86, 0xde, 0xf8, 0x22, 0x2c,
	0xb2, 0xc7, 0x30, 0xe8, 0x7e, 0xd5, 0x3f, 0x6d, 0x3a, 0x08, 0x41, 0x14, 0xec, 0x05, 0x8c, 0x3b,
	0x57, 0xe4, 0x25, 0xa9, 0x56, 0xe8, 0x3e, 0x1d, 0x86, 0x0c, 0x3a, 0x57, 0x7c, 0x8e, 0x0e, 0x7b,
	0x0b, 0x0f, 0x51, 0xb5, 0x0d, 0xf5, 0x88, 0xb9, 0x76, 0xaa, 0x40, 0x93, 0xde, 0x0f, 0x45, 0x07,
	0x37, 0xf6, 0x59, 0x70, 0x67, 0xcf, 0x61, 0x2f, 0x0c, 0x31, 0x82, 0xc1, 0x62, 0x79, 0x3a, 0x3f,
	0x3b, 0xbc, 0xc7, 0x00, 0x86, 0x8b, 0xe5, 0xe9, 0xf2, 0xfb, 0xf9, 0x61, 0x32, 0xfb, 0x93, 0xc0,
	0xa3, 0x6d, 0x0c, 0x6d, 0xd3, 0xb3, 0x0f, 0xb0, 0x8b, 0xc6, 0xac, 0x99, 0xbd, 0xfe, 0x8f, 0x99,
	0x7f, 0x05, 0x1e, 0x5e, 0x61, 0x1b, 0x9f, 0x6f, 0xf0, 0xb3, 0x5e, 0x50, 0x91, 0xdb, 0xda, 0x36,
	0xb8, 0x06, 0xb5, 0x7f, 0x41, 0xc5, 0xb9, 0xd7, 0xec, 0x15, 0x3c, 0xb8, 0xbd, 0xb4, 0x50, 0xb8,
	0x26, 0x35, 0xd9, 0x5c, 0x59, 0xa8, 0x50, 0x24, 0xb1, 0x15, 0xc6, 0xde, 0xe0, 0x8e, 0xc4, 0x26,
	0xb7, 0xe6, 0x5c, 0x9e, 0x7c, 0xfc, 0xf1, 0xbe, 0xaa, 0x6d, 0x23, 0x0a, 0x7e, 0x89, 0x5a, 0x0a,
	0x5e, 0x92, 0xe2, 0xf6, 0x3a, 0x0b, 0x22, 0x2b, 0x49, 0x29, 0xd2, 0x5d, 0xf6, 0xfb, 0x38, 0x8b,
	0xdb, 0x53, 0x51, 0x23, 0x74, 0xe5, 0x97, 0xa8, 0x18, 0x06, 0xe7, 0xdd, 0xbf, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x6a, 0xa7, 0x39, 0xac, 0x71, 0x02, 0x00, 0x00,
}
