// Code generated by protoc-gen-go. DO NOT EDIT.
// source: recipe_dump.proto

package rs

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListRecipeRequest struct {
	ID                   string      `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Factory              FactoryID   `protobuf:"varint,2,opt,name=factory,proto3,enum=proto.dm.rs.FactoryID" json:"factory,omitempty"`
	ProductType          ProductType `protobuf:"varint,3,opt,name=productType,proto3,enum=proto.dm.rs.ProductType" json:"productType,omitempty"`
	ProductID            string      `protobuf:"bytes,4,opt,name=productID,proto3" json:"productID,omitempty"`
	StageStatus          StageStatus `protobuf:"varint,5,opt,name=stageStatus,proto3,enum=proto.dm.rs.StageStatus" json:"stageStatus,omitempty"`
	SpecID               string      `protobuf:"bytes,6,opt,name=specID,proto3" json:"specID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListRecipeRequest) Reset()         { *m = ListRecipeRequest{} }
func (m *ListRecipeRequest) String() string { return proto.CompactTextString(m) }
func (*ListRecipeRequest) ProtoMessage()    {}
func (*ListRecipeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f01618e48e404415, []int{0}
}

func (m *ListRecipeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRecipeRequest.Unmarshal(m, b)
}
func (m *ListRecipeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRecipeRequest.Marshal(b, m, deterministic)
}
func (m *ListRecipeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRecipeRequest.Merge(m, src)
}
func (m *ListRecipeRequest) XXX_Size() int {
	return xxx_messageInfo_ListRecipeRequest.Size(m)
}
func (m *ListRecipeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRecipeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRecipeRequest proto.InternalMessageInfo

func (m *ListRecipeRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *ListRecipeRequest) GetFactory() FactoryID {
	if m != nil {
		return m.Factory
	}
	return FactoryID_FACTORY_UNSPECIFIED
}

func (m *ListRecipeRequest) GetProductType() ProductType {
	if m != nil {
		return m.ProductType
	}
	return ProductType_PRODUCT_TYPE_UNSPECIFIED
}

func (m *ListRecipeRequest) GetProductID() string {
	if m != nil {
		return m.ProductID
	}
	return ""
}

func (m *ListRecipeRequest) GetStageStatus() StageStatus {
	if m != nil {
		return m.StageStatus
	}
	return StageStatus_STAGE_STATUS_UNSPECIFIED
}

func (m *ListRecipeRequest) GetSpecID() string {
	if m != nil {
		return m.SpecID
	}
	return ""
}

type ListRecipeReply struct {
	Recipes              []*Recipe `protobuf:"bytes,1,rep,name=recipes,proto3" json:"recipes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListRecipeReply) Reset()         { *m = ListRecipeReply{} }
func (m *ListRecipeReply) String() string { return proto.CompactTextString(m) }
func (*ListRecipeReply) ProtoMessage()    {}
func (*ListRecipeReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_f01618e48e404415, []int{1}
}

func (m *ListRecipeReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRecipeReply.Unmarshal(m, b)
}
func (m *ListRecipeReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRecipeReply.Marshal(b, m, deterministic)
}
func (m *ListRecipeReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRecipeReply.Merge(m, src)
}
func (m *ListRecipeReply) XXX_Size() int {
	return xxx_messageInfo_ListRecipeReply.Size(m)
}
func (m *ListRecipeReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRecipeReply.DiscardUnknown(m)
}

var xxx_messageInfo_ListRecipeReply proto.InternalMessageInfo

func (m *ListRecipeReply) GetRecipes() []*Recipe {
	if m != nil {
		return m.Recipes
	}
	return nil
}

type ListSpecRequest struct {
	ID                   string      `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Factory              FactoryID   `protobuf:"varint,2,opt,name=factory,proto3,enum=proto.dm.rs.FactoryID" json:"factory,omitempty"`
	ProductType          ProductType `protobuf:"varint,3,opt,name=productType,proto3,enum=proto.dm.rs.ProductType" json:"productType,omitempty"`
	ProductID            string      `protobuf:"bytes,4,opt,name=productID,proto3" json:"productID,omitempty"`
	StageStatus          StageStatus `protobuf:"varint,5,opt,name=stageStatus,proto3,enum=proto.dm.rs.StageStatus" json:"stageStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListSpecRequest) Reset()         { *m = ListSpecRequest{} }
func (m *ListSpecRequest) String() string { return proto.CompactTextString(m) }
func (*ListSpecRequest) ProtoMessage()    {}
func (*ListSpecRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f01618e48e404415, []int{2}
}

func (m *ListSpecRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSpecRequest.Unmarshal(m, b)
}
func (m *ListSpecRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSpecRequest.Marshal(b, m, deterministic)
}
func (m *ListSpecRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSpecRequest.Merge(m, src)
}
func (m *ListSpecRequest) XXX_Size() int {
	return xxx_messageInfo_ListSpecRequest.Size(m)
}
func (m *ListSpecRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSpecRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListSpecRequest proto.InternalMessageInfo

func (m *ListSpecRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *ListSpecRequest) GetFactory() FactoryID {
	if m != nil {
		return m.Factory
	}
	return FactoryID_FACTORY_UNSPECIFIED
}

func (m *ListSpecRequest) GetProductType() ProductType {
	if m != nil {
		return m.ProductType
	}
	return ProductType_PRODUCT_TYPE_UNSPECIFIED
}

func (m *ListSpecRequest) GetProductID() string {
	if m != nil {
		return m.ProductID
	}
	return ""
}

func (m *ListSpecRequest) GetStageStatus() StageStatus {
	if m != nil {
		return m.StageStatus
	}
	return StageStatus_STAGE_STATUS_UNSPECIFIED
}

type ListSpecReply struct {
	Specs                []*Spec  `protobuf:"bytes,1,rep,name=specs,proto3" json:"specs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListSpecReply) Reset()         { *m = ListSpecReply{} }
func (m *ListSpecReply) String() string { return proto.CompactTextString(m) }
func (*ListSpecReply) ProtoMessage()    {}
func (*ListSpecReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_f01618e48e404415, []int{3}
}

func (m *ListSpecReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSpecReply.Unmarshal(m, b)
}
func (m *ListSpecReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSpecReply.Marshal(b, m, deterministic)
}
func (m *ListSpecReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSpecReply.Merge(m, src)
}
func (m *ListSpecReply) XXX_Size() int {
	return xxx_messageInfo_ListSpecReply.Size(m)
}
func (m *ListSpecReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSpecReply.DiscardUnknown(m)
}

var xxx_messageInfo_ListSpecReply proto.InternalMessageInfo

func (m *ListSpecReply) GetSpecs() []*Spec {
	if m != nil {
		return m.Specs
	}
	return nil
}

type GenerateRecipeIDRequest struct {
	Factories            []FactoryID `protobuf:"varint,1,rep,packed,name=factories,proto3,enum=proto.dm.rs.FactoryID" json:"factories,omitempty"`
	ProductType          ProductType `protobuf:"varint,2,opt,name=productType,proto3,enum=proto.dm.rs.ProductType" json:"productType,omitempty"`
	ProductID            string      `protobuf:"bytes,3,opt,name=productID,proto3" json:"productID,omitempty"`
	StageStatus          StageStatus `protobuf:"varint,4,opt,name=stageStatus,proto3,enum=proto.dm.rs.StageStatus" json:"stageStatus,omitempty"`
	Major                string      `protobuf:"bytes,5,opt,name=major,proto3" json:"major,omitempty"`
	Minor                string      `protobuf:"bytes,6,opt,name=minor,proto3" json:"minor,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GenerateRecipeIDRequest) Reset()         { *m = GenerateRecipeIDRequest{} }
func (m *GenerateRecipeIDRequest) String() string { return proto.CompactTextString(m) }
func (*GenerateRecipeIDRequest) ProtoMessage()    {}
func (*GenerateRecipeIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f01618e48e404415, []int{4}
}

func (m *GenerateRecipeIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateRecipeIDRequest.Unmarshal(m, b)
}
func (m *GenerateRecipeIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateRecipeIDRequest.Marshal(b, m, deterministic)
}
func (m *GenerateRecipeIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateRecipeIDRequest.Merge(m, src)
}
func (m *GenerateRecipeIDRequest) XXX_Size() int {
	return xxx_messageInfo_GenerateRecipeIDRequest.Size(m)
}
func (m *GenerateRecipeIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateRecipeIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateRecipeIDRequest proto.InternalMessageInfo

func (m *GenerateRecipeIDRequest) GetFactories() []FactoryID {
	if m != nil {
		return m.Factories
	}
	return nil
}

func (m *GenerateRecipeIDRequest) GetProductType() ProductType {
	if m != nil {
		return m.ProductType
	}
	return ProductType_PRODUCT_TYPE_UNSPECIFIED
}

func (m *GenerateRecipeIDRequest) GetProductID() string {
	if m != nil {
		return m.ProductID
	}
	return ""
}

func (m *GenerateRecipeIDRequest) GetStageStatus() StageStatus {
	if m != nil {
		return m.StageStatus
	}
	return StageStatus_STAGE_STATUS_UNSPECIFIED
}

func (m *GenerateRecipeIDRequest) GetMajor() string {
	if m != nil {
		return m.Major
	}
	return ""
}

func (m *GenerateRecipeIDRequest) GetMinor() string {
	if m != nil {
		return m.Minor
	}
	return ""
}

type GenerateRecipeIDReply struct {
	ID                   string                         `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Version              *GenerateRecipeIDReply_Version `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *GenerateRecipeIDReply) Reset()         { *m = GenerateRecipeIDReply{} }
func (m *GenerateRecipeIDReply) String() string { return proto.CompactTextString(m) }
func (*GenerateRecipeIDReply) ProtoMessage()    {}
func (*GenerateRecipeIDReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_f01618e48e404415, []int{5}
}

func (m *GenerateRecipeIDReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateRecipeIDReply.Unmarshal(m, b)
}
func (m *GenerateRecipeIDReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateRecipeIDReply.Marshal(b, m, deterministic)
}
func (m *GenerateRecipeIDReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateRecipeIDReply.Merge(m, src)
}
func (m *GenerateRecipeIDReply) XXX_Size() int {
	return xxx_messageInfo_GenerateRecipeIDReply.Size(m)
}
func (m *GenerateRecipeIDReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateRecipeIDReply.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateRecipeIDReply proto.InternalMessageInfo

func (m *GenerateRecipeIDReply) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *GenerateRecipeIDReply) GetVersion() *GenerateRecipeIDReply_Version {
	if m != nil {
		return m.Version
	}
	return nil
}

type GenerateRecipeIDReply_Version struct {
	Major                string   `protobuf:"bytes,1,opt,name=major,proto3" json:"major,omitempty"`
	Minor                string   `protobuf:"bytes,2,opt,name=minor,proto3" json:"minor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateRecipeIDReply_Version) Reset()         { *m = GenerateRecipeIDReply_Version{} }
func (m *GenerateRecipeIDReply_Version) String() string { return proto.CompactTextString(m) }
func (*GenerateRecipeIDReply_Version) ProtoMessage()    {}
func (*GenerateRecipeIDReply_Version) Descriptor() ([]byte, []int) {
	return fileDescriptor_f01618e48e404415, []int{5, 0}
}

func (m *GenerateRecipeIDReply_Version) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateRecipeIDReply_Version.Unmarshal(m, b)
}
func (m *GenerateRecipeIDReply_Version) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateRecipeIDReply_Version.Marshal(b, m, deterministic)
}
func (m *GenerateRecipeIDReply_Version) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateRecipeIDReply_Version.Merge(m, src)
}
func (m *GenerateRecipeIDReply_Version) XXX_Size() int {
	return xxx_messageInfo_GenerateRecipeIDReply_Version.Size(m)
}
func (m *GenerateRecipeIDReply_Version) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateRecipeIDReply_Version.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateRecipeIDReply_Version proto.InternalMessageInfo

func (m *GenerateRecipeIDReply_Version) GetMajor() string {
	if m != nil {
		return m.Major
	}
	return ""
}

func (m *GenerateRecipeIDReply_Version) GetMinor() string {
	if m != nil {
		return m.Minor
	}
	return ""
}

func init() {
	proto.RegisterType((*ListRecipeRequest)(nil), "proto.dm.rs.ListRecipeRequest")
	proto.RegisterType((*ListRecipeReply)(nil), "proto.dm.rs.ListRecipeReply")
	proto.RegisterType((*ListSpecRequest)(nil), "proto.dm.rs.ListSpecRequest")
	proto.RegisterType((*ListSpecReply)(nil), "proto.dm.rs.ListSpecReply")
	proto.RegisterType((*GenerateRecipeIDRequest)(nil), "proto.dm.rs.GenerateRecipeIDRequest")
	proto.RegisterType((*GenerateRecipeIDReply)(nil), "proto.dm.rs.GenerateRecipeIDReply")
	proto.RegisterType((*GenerateRecipeIDReply_Version)(nil), "proto.dm.rs.GenerateRecipeIDReply.Version")
}

func init() { proto.RegisterFile("recipe_dump.proto", fileDescriptor_f01618e48e404415) }

var fileDescriptor_f01618e48e404415 = []byte{
	// 451 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x94, 0xcf, 0xaa, 0xd4, 0x30,
	0x14, 0xc6, 0x69, 0xe7, 0xce, 0x0c, 0x3d, 0x83, 0x57, 0xa6, 0xea, 0xbd, 0x61, 0x70, 0x31, 0x74,
	0xe3, 0x20, 0x98, 0x4a, 0x55, 0xfc, 0xb3, 0x12, 0x29, 0x4a, 0xc1, 0x85, 0x64, 0xc4, 0x85, 0x1b,
	0xc9, 0x6d, 0x63, 0xa9, 0x4e, 0x9a, 0x9a, 0xa4, 0x57, 0x66, 0xed, 0x13, 0xf8, 0x0e, 0xbe, 0x9c,
	0x6f, 0x21, 0x4d, 0x5a, 0xda, 0x8e, 0x23, 0xa2, 0xcb, 0xbb, 0x2a, 0xe7, 0x9c, 0xef, 0x7c, 0xfd,
	0xf2, 0x23, 0x04, 0x96, 0x92, 0xa5, 0x45, 0xc5, 0x3e, 0x64, 0x35, 0xaf, 0x70, 0x25, 0x85, 0x16,
	0xfe, 0xc2, 0x7c, 0x70, 0xc6, 0xb1, 0x54, 0xab, 0x73, 0x53, 0x84, 0x19, 0x0f, 0xa5, 0x0a, 0x59,
	0x59, 0x73, 0x65, 0x55, 0x2b, 0x34, 0x1c, 0x58, 0x13, 0x3b, 0x09, 0xbe, 0xb9, 0xb0, 0x7c, 0x5d,
	0x28, 0x4d, 0x4c, 0x93, 0xb0, 0x2f, 0x35, 0x53, 0xda, 0x3f, 0x05, 0x37, 0x89, 0x91, 0xb3, 0x76,
	0x36, 0x1e, 0x71, 0x93, 0xd8, 0xbf, 0x0f, 0xf3, 0x8f, 0x34, 0xd5, 0x42, 0xee, 0x91, 0xbb, 0x76,
	0x36, 0xa7, 0xd1, 0x19, 0x1e, 0xfc, 0x17, 0xbf, 0xb4, 0xb3, 0x24, 0x26, 0x9d, 0xcc, 0x7f, 0x06,
	0x4d, 0xb2, 0xac, 0x4e, 0xf5, 0xdb, 0x7d, 0xc5, 0xd0, 0xc4, 0x6c, 0xa1, 0xd1, 0xd6, 0x9b, 0x7e,
	0x4e, 0x86, 0x62, 0xff, 0x36, 0x78, 0x6d, 0x99, 0xc4, 0xe8, 0xc4, 0x84, 0xe8, 0x1b, 0x8d, 0xb3,
	0xd2, 0x34, 0x67, 0x5b, 0x4d, 0x75, 0xad, 0xd0, 0xf4, 0x88, 0xf3, 0xb6, 0x9f, 0x93, 0xa1, 0xd8,
	0x3f, 0x83, 0x99, 0xaa, 0x58, 0x9a, 0xc4, 0x68, 0x66, 0x6c, 0xdb, 0x2a, 0x78, 0x0e, 0xd7, 0x87,
	0x10, 0xaa, 0xdd, 0xde, 0xbf, 0x07, 0x73, 0x0b, 0x4a, 0x21, 0x67, 0x3d, 0xd9, 0x2c, 0xa2, 0x1b,
	0xa3, 0x5f, 0xb4, 0xd2, 0x4e, 0x13, 0xfc, 0x74, 0xac, 0xc5, 0xb6, 0x62, 0xe9, 0x15, 0xa7, 0x18,
	0x3c, 0x81, 0x6b, 0xfd, 0x51, 0x1b, 0x56, 0x77, 0x60, 0xda, 0x80, 0xec, 0x48, 0x2d, 0xc7, 0x36,
	0x8d, 0xcc, 0xce, 0x83, 0xef, 0x2e, 0x9c, 0xbf, 0x62, 0x25, 0x93, 0x54, 0x33, 0x4b, 0x30, 0x89,
	0x3b, 0x5a, 0x0f, 0xc1, 0xb3, 0xc7, 0x2e, 0x5a, 0xe4, 0x7f, 0xe6, 0xd3, 0x0b, 0x0f, 0x09, 0xb9,
	0xff, 0x4d, 0x68, 0xf2, 0x17, 0x42, 0x27, 0xff, 0x72, 0xcf, 0x6e, 0xc2, 0x94, 0xd3, 0x4f, 0x42,
	0x1a, 0xae, 0x1e, 0xb1, 0x85, 0xe9, 0x16, 0xa5, 0x90, 0xed, 0xe5, 0xb3, 0x45, 0xf0, 0xc3, 0x81,
	0x5b, 0xbf, 0x33, 0x69, 0xb0, 0x1e, 0xde, 0x9f, 0x18, 0xe6, 0x97, 0x4c, 0xaa, 0x42, 0x94, 0xe6,
	0x9c, 0x8b, 0xe8, 0xee, 0x28, 0xcd, 0x51, 0x13, 0xfc, 0xce, 0x6e, 0x90, 0x6e, 0x75, 0xf5, 0x08,
	0xe6, 0x6d, 0xaf, 0x8f, 0xe9, 0x1c, 0x8d, 0xe9, 0x0e, 0x62, 0xbe, 0x78, 0xfa, 0xfe, 0x71, 0x5e,
	0xe8, 0x1d, 0xbd, 0xc0, 0x9f, 0x59, 0x99, 0x51, 0x9c, 0x0a, 0x8e, 0xf5, 0xd7, 0xd0, 0x14, 0x61,
	0x2a, 0x38, 0x17, 0xa5, 0x0a, 0x2f, 0xa3, 0xd0, 0xbe, 0x34, 0xb9, 0xd8, 0xd1, 0x32, 0xb7, 0x0f,
	0xce, 0xc5, 0xcc, 0xf4, 0x1e, 0xfc, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x51, 0x02, 0x88, 0x82, 0xbf,
	0x04, 0x00, 0x00,
}
